//! # Read-Write-Guard Architecture
//!
//! The Read-Write-Guard stage acts as a defensive shield around ecosystem
//! lockfiles and manifests, on both ends: it stops the agent from manually
//! *writing* them, and discourages it from *reading* them directly.
//!
//! ## Core Design
//!
//! Many AI agents natively attempt to `Write` or `Edit` files like
//! `flake.lock` or `Cargo.lock` when told to update dependencies. These files
//! are typically autogenerated and manually editing them can easily break
//! build reproducibility or introduce subtle hash-mismatch errors. Reading
//! them is similarly unproductive: they're large, dense, and provide little
//! signal relative to the context they consume.
//!
//! Read-Write-Guard intercepts both:
//! - **Writes** are denied and redirected to the proper ecosystem-native
//!   tooling (e.g. `nix flake update`, `cargo update`, `npm install`).
//! - **Reads** are denied with a generic reminder that the file is
//!   machine-generated noise, pointing the agent at `git diff` instead.
//!
//! ## Supported Ecosystems
//! * **Nix**: `flake.lock`
//! * **Node.js**: `package-lock.json`, `yarn.lock`, `pnpm-lock.yaml`,
//!   `bun.lock`, `bun.lockb`
//! * **Rust**: `Cargo.lock`
//! * **Python**: `poetry.lock`, `Pipfile.lock`, `uv.lock`
//! * **Go**: `go.sum`
//! * **Other**: `Gemfile.lock`, `composer.lock`, `mix.lock`, `pubspec.lock`, `.terraform.lock.hcl`
//!
//! ## Implementation Details
//!
//! 1. **Target Identification**: Filters `PreToolUse` events for both
//!    modifying tools (`Write`, `Edit`, `MultiEdit`, `write_file`, `replace`)
//!    and reading tools (`READ_TOOLS`).
//! 2. **Path Matching**: Looks up the target file's name in `RuleSet`, a
//!    `BTreeMap`-backed index of `Rule`s (one per guarded filename) — no
//!    linear scan over the supported ecosystems.
//! 3. **Response Generation**: Each `Rule` carries an [`Access`] policy
//!    that determines, per tool kind, whether the action is denied and what
//!    the denial reason looks like — modifying tools get a targeted hint
//!    containing the correct terminal command to use instead; reading tools
//!    get a generic "this is noise, use `git diff`" reminder. All built-in
//!    rules use [`Access::No`] (deny both, with those two messages).
//!
//! [`Access::Diff`] is a reserved policy for config.json-defined rules (or a
//! future upgrade of the built-ins): it's meant to replace the generic
//! read-denial with a real diff/summary once that's implemented. For now it
//! behaves identically to [`Access::No`].
//! [`FlakeLockSummarizationStage`](crate::FlakeLockSummarizationStage),
//! registered earlier in the pipeline, already provides this kind of summary
//! for `flake.lock` reads specifically — this stage's [`Access::No`]
//! read-deny is the fallback for everything else (and for `flake.lock` when
//! that stage is a no-op).

use inceptool_engine::{EngineError, Stage};
use inceptool_protocol::{
    Conn, Decision, HookInputEvent, HookKind, HookOutputEvent, PreToolUseOutput, extract_file_path,
};

use serde::Deserialize;
use serde_json::Value;

use std::borrow::Cow;
use std::collections::BTreeMap;
use std::sync::LazyLock;

/// Tool names whose `PreToolUse` event reads a file's contents.
const READ_TOOLS: &[&str] = &["Read", "view_file", "cat"];

/// Stage that denies direct reads and writes of ecosystem lockfiles.
#[derive(Debug, Clone, Copy, Default)]
pub struct ReadWriteGuardStage;

impl Stage for ReadWriteGuardStage {
    fn name(&self) -> &'static str {
        "read-write-guard"
    }

    fn hook(&self) -> HookKind {
        HookKind::PreToolUse
    }

    fn tool_names(&self) -> &'static [&'static str] {
        &[
            "Write",
            "Edit",
            "MultiEdit",
            "write_file",
            "replace",
            "Read",
            "view_file",
            "cat",
        ]
    }

    fn run(&self, conn: &mut Conn<'_>) -> Result<Option<HookOutputEvent>, EngineError> {
        if let HookInputEvent::PreToolUse(input) = &conn.event {
            let parsed: Value = input.parse_tool_input()?;

            let Some(file_path) = extract_file_path(&parsed) else {
                return Ok(None);
            };

            let file_name = file_path.split('/').next_back().unwrap_or(file_path);

            let Some(rule) = RULES.get(file_name) else {
                return Ok(None);
            };

            let is_read_tool = READ_TOOLS.contains(&input.tool_name.as_ref());

            let Some(output) = dispatch(file_name, rule, is_read_tool) else {
                return Ok(None);
            };

            return Ok(Some(HookOutputEvent::PreToolUse(output)));
        }
        Ok(None)
    }
}

/// Access policy for a guarded file, driving how [`ReadWriteGuardStage`]
/// responds to reads and writes of it.
#[derive(Debug, Clone, PartialEq, Eq, Deserialize)]
#[serde(rename_all = "snake_case")]
pub enum Access {
    /// Deny both reads and writes. Reads get a flat, no-frills reason
    /// pointing at `git diff`; writes get `hint` and `note`. The policy used
    /// by all built-in rules.
    No {
        /// The terminal command suggested when a write is denied.
        hint: Cow<'static, str>,
        /// Additional caveats about the scope of `hint` (e.g. "updates ALL
        /// packages").
        note: Cow<'static, str>,
    },
    /// Like [`Access::No`], but reads are intended to get a richer
    /// diff/summary instead of the flat reason, once diff-content generation
    /// exists. Currently degrades to [`Access::No`]'s read behavior.
    /// Reserved for config.json-defined rules (or a future upgrade of the
    /// built-ins).
    Diff {
        /// The terminal command suggested when a write is denied.
        hint: Cow<'static, str>,
        /// Additional caveats about the scope of `hint`.
        note: Cow<'static, str>,
    },
    /// Deny writes only (with `hint` and `note`); reads pass through
    /// untouched.
    Write {
        /// The terminal command suggested when a write is denied.
        hint: Cow<'static, str>,
        /// Additional caveats about the scope of `hint`.
        note: Cow<'static, str>,
    },
    /// Deny reads only (flat reason); writes pass through untouched.
    Read,
}

/// A guarded-file rule: how [`ReadWriteGuardStage`] responds to reads and
/// writes of [`Rule::filename`].
#[derive(Debug, Clone, PartialEq, Eq)]
struct Rule {
    /// The filename this rule matches (e.g. `"Cargo.lock"`).
    filename: Cow<'static, str>,
    /// Which operations are intercepted, and how.
    access: Access,
}

/// Index of [`Rule`]s by [`Rule::filename`], built via [`FromIterator`].
struct RuleSet(BTreeMap<Cow<'static, str>, Rule>);

impl FromIterator<Rule> for RuleSet {
    fn from_iter<I>(iter: I) -> Self
    where
        I: IntoIterator<Item = Rule>,
    {
        Self(
            iter.into_iter()
                .map(|rule| (rule.filename.clone(), rule))
                .collect(),
        )
    }
}

impl RuleSet {
    /// Looks up the [`Rule`] for `file_name`, or `None` if it isn't guarded.
    fn get(&self, file_name: &str) -> Option<&Rule> {
        self.0.get(file_name)
    }
}

/// The built-in guarded-file rules, indexed by filename.
static RULES: LazyLock<RuleSet> = LazyLock::new(|| {
    [
        // Nix
        Rule {
            filename: Cow::Borrowed("flake.lock"),
            access: Access::No {
                hint: Cow::Borrowed("Run `nix flake update` to update it."),
                note: Cow::Borrowed("(NOTE: this updates ALL flake inputs \u{2014} use `nix flake update <name>` to update a specific one)"),
            },
        },
        // Node
        Rule {
            filename: Cow::Borrowed("package-lock.json"),
            access: Access::No {
                hint: Cow::Borrowed("Run `npm install` to update it."),
                note: Cow::Borrowed("(NOTE: this updates ALL node packages)"),
            },
        },
        Rule {
            filename: Cow::Borrowed("yarn.lock"),
            access: Access::No {
                hint: Cow::Borrowed("Run `yarn install` to update it."),
                note: Cow::Borrowed("(NOTE: this updates ALL node packages)"),
            },
        },
        Rule {
            filename: Cow::Borrowed("pnpm-lock.yaml"),
            access: Access::No {
                hint: Cow::Borrowed("Run `pnpm install` to update it."),
                note: Cow::Borrowed("(NOTE: this updates ALL node packages)"),
            },
        },
        Rule {
            filename: Cow::Borrowed("bun.lock"),
            access: Access::No {
                hint: Cow::Borrowed("Run `bun install` to update it."),
                note: Cow::Borrowed("(NOTE: this updates ALL node packages)"),
            },
        },
        Rule {
            filename: Cow::Borrowed("bun.lockb"),
            access: Access::No {
                hint: Cow::Borrowed("Run `bun install` to update it."),
                note: Cow::Borrowed("(NOTE: this updates ALL node packages)"),
            },
        },
        // Rust
        Rule {
            filename: Cow::Borrowed("Cargo.lock"),
            access: Access::No {
                hint: Cow::Borrowed("Run `cargo update` to update it."),
                note: Cow::Borrowed("(NOTE: this updates ALL Rust dependencies \u{2014} use `cargo update -p <name> --precise <ver>` for one)"),
            },
        },
        // Python
        Rule {
            filename: Cow::Borrowed("poetry.lock"),
            access: Access::No {
                hint: Cow::Borrowed("Run `poetry lock` to update it."),
                note: Cow::Borrowed("(NOTE: this updates ALL Python packages)"),
            },
        },
        Rule {
            filename: Cow::Borrowed("Pipfile.lock"),
            access: Access::No {
                hint: Cow::Borrowed("Run `pipenv lock` to update it."),
                note: Cow::Borrowed("(NOTE: this updates ALL Python packages)"),
            },
        },
        Rule {
            filename: Cow::Borrowed("uv.lock"),
            access: Access::No {
                hint: Cow::Borrowed("Run `uv lock` to update it."),
                note: Cow::Borrowed("(NOTE: this updates ALL Python packages)"),
            },
        },
        // Go
        Rule {
            filename: Cow::Borrowed("go.sum"),
            access: Access::No {
                hint: Cow::Borrowed("Run `go mod tidy` to update it."),
                note: Cow::Borrowed("(NOTE: this updates ALL Go modules \u{2014} use `go get <module>@<ver>` for one)"),
            },
        },
        // Other
        Rule {
            filename: Cow::Borrowed("Gemfile.lock"),
            access: Access::No {
                hint: Cow::Borrowed("Run `bundle install` to update it."),
                note: Cow::Borrowed("(NOTE: this updates ALL Ruby gems \u{2014} use `bundle update <gem>` for one)"),
            },
        },
        Rule {
            filename: Cow::Borrowed("composer.lock"),
            access: Access::No {
                hint: Cow::Borrowed("Run `composer install` to update it."),
                note: Cow::Borrowed("(NOTE: this updates ALL dependencies at once)"),
            },
        },
        Rule {
            filename: Cow::Borrowed("mix.lock"),
            access: Access::No {
                hint: Cow::Borrowed("Run `mix deps.get` to update it."),
                note: Cow::Borrowed("(NOTE: this updates ALL dependencies at once)"),
            },
        },
        Rule {
            filename: Cow::Borrowed("pubspec.lock"),
            access: Access::No {
                hint: Cow::Borrowed("Run `dart pub get` to update it."),
                note: Cow::Borrowed("(NOTE: this updates ALL dependencies at once)"),
            },
        },
        Rule {
            filename: Cow::Borrowed(".terraform.lock.hcl"),
            access: Access::No {
                hint: Cow::Borrowed("Run `terraform init -upgrade` to update it."),
                note: Cow::Borrowed("(NOTE: this updates ALL dependencies at once)"),
            },
        },
    ]
    .into_iter()
    .collect()
});

/// Dispatches a guarded-file access: returns the [`Decision::Deny`] response
/// for `rule`'s policy and the current tool kind, or `None` if `rule.access`
/// allows this operation to pass through untouched.
fn dispatch(file_name: &str, rule: &Rule, is_read_tool: bool) -> Option<PreToolUseOutput> {
    match (&rule.access, is_read_tool) {
        (Access::Write { .. }, true) | (Access::Read, false) => None,
        (_, true) => Some(deny_read(file_name)),
        (
            Access::No { hint, note } | Access::Diff { hint, note } | Access::Write { hint, note },
            false,
        ) => Some(deny_write(file_name, hint, note)),
    }
}

/// Builds the [`Decision::Deny`] response for a denied read of `file_name`.
fn deny_read(file_name: &str) -> PreToolUseOutput {
    PreToolUseOutput {
        decision: Some(Decision::Deny),
        reason: Some(
            format!(
                "Reading {file_name} directly wastes context \u{2014} it's a \
                 machine-generated lockfile with little useful signal. Run \
                 `git diff {file_name}` to see what changed."
            )
            .into(),
        ),
        ..Default::default()
    }
}

/// Builds the [`Decision::Deny`] response for a denied write of `file_name`,
/// using the matched [`Access`] variant's `hint` and `note`.
fn deny_write(file_name: &str, hint: &str, note: &str) -> PreToolUseOutput {
    PreToolUseOutput {
        decision: Some(Decision::Deny),
        reason: Some(format!("Writing to {file_name} is not allowed. {hint} {note}").into()),
        ..Default::default()
    }
}

#[cfg(test)]
mod tests {
    use super::*;

    use inceptool_protocol::{BeforeAgentInput, PreToolUseInput, RawJson, SessionMeta};

    use rstest::rstest;
    use serde_json::json;
    use serde_json::value::RawValue;

    use std::collections::BTreeSet;

    #[derive(thiserror::Error, Debug)]
    enum TestError {
        #[error(transparent)]
        Engine(#[from] EngineError),
        #[error(transparent)]
        Json(#[from] serde_json::Error),
        #[error("Test failure: {0}")]
        Failure(String),
    }

    /// Builds a synthetic `Conn` wrapping `event`, with placeholder session metadata.
    fn conn_with_event(event: HookInputEvent<'_>) -> Conn<'_> {
        Conn {
            session: SessionMeta {
                session_id: Cow::Borrowed("session-1"),
                transcript_path: None,
                cwd: None,
                timestamp: None,
                driver: Cow::Borrowed("Test"),
                driver_meta: None,
                permission_mode: None,
                effort: None,
                agent_id: None,
                agent_type: None,
            },
            event,
        }
    }

    /// Runs [`ReadWriteGuardStage`] against a synthetic `PreToolUse` event for
    /// `tool_name` with the given `tool_input_json` (e.g. `{"file_path": "..."}`).
    fn run_stage_with_tool_input(
        tool_name: &str,
        tool_input_json: &str,
    ) -> Result<Option<HookOutputEvent>, TestError> {
        let stage = ReadWriteGuardStage;
        let tool_input = RawValue::from_string(tool_input_json.to_owned())?;

        let mut conn = conn_with_event(HookInputEvent::PreToolUse(PreToolUseInput {
            tool_name: Cow::Borrowed(tool_name),
            tool_input: RawJson(&tool_input),
            mcp_context: None,
            original_request_name: None,
        }));

        Ok(stage.run(&mut conn)?)
    }

    /// Runs [`ReadWriteGuardStage`] against a synthetic `PreToolUse` event for
    /// `tool_name` targeting `file_path`.
    fn run_stage(tool_name: &str, file_path: &str) -> Result<Option<HookOutputEvent>, TestError> {
        run_stage_with_tool_input(tool_name, &json!({"file_path": file_path}).to_string())
    }

    /// Extracts the `reason` from a `PreToolUse` `Deny` output, failing the test otherwise.
    fn deny_reason(output: Option<HookOutputEvent>) -> Result<String, TestError> {
        let HookOutputEvent::PreToolUse(pre) =
            output.ok_or_else(|| TestError::Failure("expected a hook output".into()))?
        else {
            return Err(TestError::Failure("expected a PreToolUse output".into()));
        };

        assert_eq!(pre.decision, Some(Decision::Deny));

        pre.reason
            .map(Cow::into_owned)
            .ok_or_else(|| TestError::Failure("missing reason".into()))
    }

    /// Builds a synthetic [`Rule`] with `access`, for exercising [`dispatch`]
    /// directly without going through [`RULES`].
    const fn rule_with_access(access: Access) -> Rule {
        Rule {
            filename: Cow::Borrowed("test.lock"),
            access,
        }
    }

    #[rstest]
    #[case::flake_lock("flake.lock", "nix flake update")]
    #[case::cargo_lock("Cargo.lock", "cargo update")]
    #[case::package_lock("package-lock.json", "npm install")]
    fn denies_write_with_hint(
        #[case] file_name: &str,
        #[case] hint_fragment: &str,
    ) -> Result<(), TestError> {
        let reason = deny_reason(run_stage("Edit", &format!("/repo/{file_name}"))?)?;

        assert!(reason.starts_with(&format!("Writing to {file_name} is not allowed.")));
        assert!(reason.contains(hint_fragment));

        Ok(())
    }

    #[rstest]
    #[case::flake_lock("flake.lock")]
    #[case::cargo_lock("Cargo.lock")]
    #[case::package_lock("package-lock.json")]
    fn denies_read_with_generic_reason(#[case] file_name: &str) -> Result<(), TestError> {
        let reason = deny_reason(run_stage("Read", &format!("/repo/{file_name}"))?)?;

        assert!(reason.starts_with(&format!("Reading {file_name} directly wastes context")));
        assert!(reason.contains(&format!("git diff {file_name}")));

        Ok(())
    }

    #[rstest]
    #[case::write_tool("Write")]
    #[case::read_tool("Read")]
    fn ignores_unguarded_file(#[case] tool_name: &str) -> Result<(), TestError> {
        assert!(run_stage(tool_name, "/repo/src/main.rs")?.is_none());
        Ok(())
    }

    #[rstest]
    #[case::write_tool("Write")]
    #[case::read_tool("Read")]
    fn ignores_missing_file_path(#[case] tool_name: &str) -> Result<(), TestError> {
        assert!(run_stage_with_tool_input(tool_name, "{}")?.is_none());
        Ok(())
    }

    #[rstest]
    fn ignores_non_pre_tool_use_event() -> Result<(), TestError> {
        let stage = ReadWriteGuardStage;

        let mut conn = conn_with_event(HookInputEvent::BeforeAgent(BeforeAgentInput {
            prompt: Cow::Borrowed("rm -rf /"),
        }));

        assert!(stage.run(&mut conn)?.is_none());

        Ok(())
    }

    /// Tool names whose `PreToolUse` event writes a file's contents.
    const WRITE_TOOLS: &[&str] = &["Write", "Edit", "MultiEdit", "write_file", "replace"];

    #[rstest]
    fn tool_names_matches_read_and_write_tools() {
        let stage = ReadWriteGuardStage;

        let expected: BTreeSet<&str> = READ_TOOLS.iter().chain(WRITE_TOOLS).copied().collect();
        let actual: BTreeSet<&str> = stage.tool_names().iter().copied().collect();

        assert_eq!(actual, expected);
    }

    #[rstest]
    #[case::flake_lock("flake.lock")]
    #[case::package_lock_json("package-lock.json")]
    #[case::yarn_lock("yarn.lock")]
    #[case::pnpm_lock("pnpm-lock.yaml")]
    #[case::bun_lock("bun.lock")]
    #[case::bun_lockb("bun.lockb")]
    #[case::cargo_lock("Cargo.lock")]
    #[case::poetry_lock("poetry.lock")]
    #[case::pipfile_lock("Pipfile.lock")]
    #[case::uv_lock("uv.lock")]
    #[case::go_sum("go.sum")]
    #[case::gemfile_lock("Gemfile.lock")]
    #[case::composer_lock("composer.lock")]
    #[case::mix_lock("mix.lock")]
    #[case::pubspec_lock("pubspec.lock")]
    #[case::terraform_lock(".terraform.lock.hcl")]
    fn rules_recognize_all_supported_lockfiles(#[case] file_name: &str) {
        assert!(RULES.get(file_name).is_some());
    }

    #[rstest]
    fn rules_return_none_for_unknown_file() {
        assert!(RULES.get("main.rs").is_none());
    }

    #[rstest]
    #[case::no(Access::No { hint: Cow::Borrowed("<hint>"), note: Cow::Borrowed("<note>") })]
    #[case::diff(Access::Diff { hint: Cow::Borrowed("<hint>"), note: Cow::Borrowed("<note>") })]
    #[case::read(Access::Read)]
    fn dispatch_denies_read_with_generic_reason(#[case] access: Access) -> Result<(), TestError> {
        let rule = rule_with_access(access);
        let output = dispatch("test.lock", &rule, true)
            .ok_or_else(|| TestError::Failure("expected a deny".into()))?;

        assert_eq!(output.decision, Some(Decision::Deny));

        let reason = output
            .reason
            .map(Cow::into_owned)
            .ok_or_else(|| TestError::Failure("missing reason".into()))?;
        assert!(reason.starts_with("Reading test.lock directly wastes context"));
        assert!(reason.contains("git diff test.lock"));

        Ok(())
    }

    #[rstest]
    #[case::no(Access::No { hint: Cow::Borrowed("<hint>"), note: Cow::Borrowed("<note>") })]
    #[case::diff(Access::Diff { hint: Cow::Borrowed("<hint>"), note: Cow::Borrowed("<note>") })]
    #[case::write(Access::Write { hint: Cow::Borrowed("<hint>"), note: Cow::Borrowed("<note>") })]
    fn dispatch_denies_write_with_hint(#[case] access: Access) -> Result<(), TestError> {
        let rule = rule_with_access(access);
        let output = dispatch("test.lock", &rule, false)
            .ok_or_else(|| TestError::Failure("expected a deny".into()))?;

        assert_eq!(output.decision, Some(Decision::Deny));

        let reason = output
            .reason
            .map(Cow::into_owned)
            .ok_or_else(|| TestError::Failure("missing reason".into()))?;
        assert!(reason.starts_with("Writing to test.lock is not allowed."));
        assert!(reason.contains("<hint>"));
        assert!(reason.contains("<note>"));

        Ok(())
    }

    #[rstest]
    #[case::write_access_read_tool(Access::Write { hint: Cow::Borrowed("<hint>"), note: Cow::Borrowed("<note>") }, true)]
    #[case::read_access_write_tool(Access::Read, false)]
    fn dispatch_passes_through_unrestricted_operation(
        #[case] access: Access,
        #[case] is_read_tool: bool,
    ) {
        let rule = rule_with_access(access);
        assert!(dispatch("test.lock", &rule, is_read_tool).is_none());
    }
}
