//! Defines the driver trait abstractions for agent backends.

use crate::error::ProtocolError;
use crate::output::HookOutputEvent;
use crate::session::Conn;

/// An abstraction over a specific backend driver (e.g., Claude or Gemini).
///
/// The `Driver` trait provides the necessary methods to convert raw JSON strings
/// from the backend into canonical protocol objects (`Conn`), and format the hook
/// results back into the JSON format expected by the backend.
pub trait Driver {
    /// Parses a raw JSON payload from the backend into a standardized `Conn` object.
    ///
    /// # Arguments
    ///
    /// * `raw_json` - A string slice containing the raw JSON payload to parse.
    ///
    /// # Returns
    ///
    /// A `Result` containing the parsed `Conn` or a `ProtocolError` if parsing fails.
    fn parse<'a>(&self, raw_json: &'a str) -> Result<Conn<'a>, ProtocolError>;

    /// Formats the canonical hook output back into the backend-specific JSON protocol.
    ///
    /// # Arguments
    ///
    /// * `event_name` - The name of the event being responded to.
    /// * `output` - The canonical output generated by the hooks.
    ///
    /// # Returns
    ///
    /// A `Result` containing the formatted JSON string or a `ProtocolError`.
    fn format_output(
        &self,
        event_name: &str,
        output: HookOutputEvent,
    ) -> Result<String, ProtocolError>;
}
