//! Definitions for all output payloads returned by hooks.

use crate::types::Decision;

use serde::Serialize;
use serde_json::Value;

/// Represents the overall output from any hook.
///
/// This enum is untagged so it serializes directly into the underlying variant's structure.
#[derive(Debug, Serialize)]
#[serde(untagged)]
pub enum HookOutputEvent {
    /// Output for a `BeforeTool` event.
    BeforeTool(BeforeToolOutput),
    /// Output for an `AfterTool` event.
    AfterTool(AfterToolOutput),
    /// Output for a `BeforeAgent` event.
    BeforeAgent(BeforeAgentOutput),
    /// Output for an `AfterAgent` event.
    AfterAgent(AfterAgentOutput),
    /// Output for a `BeforeModel` event.
    BeforeModel(BeforeModelOutput),
    /// Output for an `AfterModel` event.
    AfterModel(AfterModelOutput),
    /// Output for a `BeforeToolSelection` event.
    BeforeToolSelection(BeforeToolSelectionOutput),
    /// Output for a `SessionStart` event.
    SessionStart(SessionStartOutput),
    /// Output for a `SessionEnd` event.
    SessionEnd(SessionEndOutput),
    /// Output for a `Notification` event.
    Notification(NotificationOutput),
    /// Output for a `PreCompress` event.
    PreCompress(PreCompressOutput),
    /// Output for a `CwdChanged` event.
    CwdChanged(CwdChangedOutput),
    /// Output for a `FileChanged` event.
    FileChanged(FileChangedOutput),
    /// Output for an `InstructionsLoaded` event.
    InstructionsLoaded(InstructionsLoadedOutput),
    /// Output for a `UserPromptSubmit` event.
    UserPromptSubmit(UserPromptSubmitOutput),
    /// Output for a `WorktreeCreate` event.
    WorktreeCreate(WorktreeCreateOutput),
    /// Output for a `WorktreeRemove` event.
    WorktreeRemove(WorktreeRemoveOutput),
}

/// The response generated by a `BeforeTool` hook.
#[derive(Debug, Default, Serialize)]
pub struct BeforeToolOutput {
    /// The hook's decision on whether to allow the tool execution.
    #[serde(skip_serializing_if = "Option::is_none")]
    pub decision: Option<Decision>,
    /// The reason for the decision, if any.
    #[serde(skip_serializing_if = "Option::is_none")]
    pub reason: Option<String>,
    /// Overridden input arguments for the tool.
    #[serde(skip_serializing_if = "Option::is_none")]
    pub updated_input: Option<Value>,
    /// Additional context injected into the prompt.
    #[serde(skip_serializing_if = "Option::is_none")]
    pub additional_context: Option<String>,
    /// Indicates whether to halt the process entirely.
    #[serde(skip_serializing_if = "Option::is_none")]
    pub halt: Option<bool>,
    /// An exit code to return if halting.
    #[serde(skip_serializing_if = "Option::is_none")]
    pub exit_code: Option<i32>,
}

/// The response generated by an `AfterTool` hook.
#[derive(Debug, Default, Serialize)]
pub struct AfterToolOutput {
    /// The hook's decision based on the tool's output.
    #[serde(skip_serializing_if = "Option::is_none")]
    pub decision: Option<Decision>,
    /// The reason for the decision, if any.
    #[serde(skip_serializing_if = "Option::is_none")]
    pub reason: Option<String>,
    /// Additional context injected into the prompt.
    #[serde(skip_serializing_if = "Option::is_none")]
    pub additional_context: Option<String>,
    /// Overridden output returned to the model.
    #[serde(skip_serializing_if = "Option::is_none")]
    pub updated_tool_output: Option<Value>,
    /// If true, suppresses the tool's actual output from the model.
    #[serde(skip_serializing_if = "Option::is_none")]
    pub suppress_output: Option<bool>,
    /// Indicates whether to halt the process entirely.
    #[serde(skip_serializing_if = "Option::is_none")]
    pub halt: Option<bool>,
    /// An exit code to return if halting.
    #[serde(skip_serializing_if = "Option::is_none")]
    pub exit_code: Option<i32>,
}

/// The response generated by a `BeforeAgent` hook.
#[derive(Debug, Default, Serialize)]
pub struct BeforeAgentOutput {
    /// The hook's decision on whether to allow the agent to start.
    #[serde(skip_serializing_if = "Option::is_none")]
    pub decision: Option<Decision>,
    /// The reason for the decision, if any.
    #[serde(skip_serializing_if = "Option::is_none")]
    pub reason: Option<String>,
    /// Additional context to inject before the agent starts.
    #[serde(skip_serializing_if = "Option::is_none")]
    pub additional_context: Option<String>,
    /// Indicates whether to halt the process entirely.
    #[serde(skip_serializing_if = "Option::is_none")]
    pub halt: Option<bool>,
    /// An exit code to return if halting.
    #[serde(skip_serializing_if = "Option::is_none")]
    pub exit_code: Option<i32>,
}

/// The response generated by an `AfterAgent` hook.
#[derive(Debug, Default, Serialize)]
pub struct AfterAgentOutput {
    /// The hook's decision based on the agent's run.
    #[serde(skip_serializing_if = "Option::is_none")]
    pub decision: Option<Decision>,
    /// The reason for the decision, if any.
    #[serde(skip_serializing_if = "Option::is_none")]
    pub reason: Option<String>,
    /// Indicates if the context should be cleared.
    #[serde(skip_serializing_if = "Option::is_none")]
    pub clear_context: Option<bool>,
    /// Indicates whether to halt the process entirely.
    #[serde(skip_serializing_if = "Option::is_none")]
    pub halt: Option<bool>,
    /// An exit code to return if halting.
    #[serde(skip_serializing_if = "Option::is_none")]
    pub exit_code: Option<i32>,
}

/// The response generated by a `BeforeModel` hook.
#[derive(Debug, Default, Serialize)]
pub struct BeforeModelOutput {
    /// The hook's decision on whether to proceed with the model request.
    #[serde(skip_serializing_if = "Option::is_none")]
    pub decision: Option<Decision>,
    /// The reason for the decision.
    #[serde(skip_serializing_if = "Option::is_none")]
    pub reason: Option<String>,
    /// A modified LLM request to use instead of the original.
    #[serde(skip_serializing_if = "Option::is_none")]
    pub llm_request: Option<Value>,
    /// A stubbed LLM response to return immediately without calling the API.
    #[serde(skip_serializing_if = "Option::is_none")]
    pub llm_response: Option<Value>,
    /// Indicates whether to halt the process entirely.
    #[serde(skip_serializing_if = "Option::is_none")]
    pub halt: Option<bool>,
    /// An exit code to return if halting.
    #[serde(skip_serializing_if = "Option::is_none")]
    pub exit_code: Option<i32>,
}

/// The response generated by an `AfterModel` hook.
#[derive(Debug, Default, Serialize)]
pub struct AfterModelOutput {
    /// The hook's decision on how to handle the model's response.
    #[serde(skip_serializing_if = "Option::is_none")]
    pub decision: Option<Decision>,
    /// The reason for the decision.
    #[serde(skip_serializing_if = "Option::is_none")]
    pub reason: Option<String>,
    /// A modified LLM response to use instead of the original.
    #[serde(skip_serializing_if = "Option::is_none")]
    pub llm_response: Option<Value>,
    /// Indicates whether to halt the process entirely.
    #[serde(skip_serializing_if = "Option::is_none")]
    pub halt: Option<bool>,
    /// An exit code to return if halting.
    #[serde(skip_serializing_if = "Option::is_none")]
    pub exit_code: Option<i32>,
}

/// The response generated by a `BeforeToolSelection` hook.
#[derive(Debug, Default, Serialize)]
pub struct BeforeToolSelectionOutput {
    /// Modified tool configurations to provide to the model.
    #[serde(skip_serializing_if = "Option::is_none")]
    pub tool_config: Option<Value>,
}

/// The response generated by a `SessionStart` hook.
#[derive(Debug, Default, Serialize)]
pub struct SessionStartOutput {
    /// Additional context to start the session with.
    #[serde(skip_serializing_if = "Option::is_none")]
    pub additional_context: Option<String>,
    /// A system message to output to the user.
    #[serde(skip_serializing_if = "Option::is_none")]
    pub system_message: Option<String>,
    /// Environment variables to persist.
    #[serde(skip_serializing_if = "Option::is_none")]
    pub persist_env: Option<Value>,
}

/// The response generated by a `SessionEnd` hook.
#[derive(Debug, Default, Serialize)]
pub struct SessionEndOutput {
    /// A final system message to output to the user.
    #[serde(skip_serializing_if = "Option::is_none")]
    pub system_message: Option<String>,
}

/// The response generated by a `Notification` hook.
#[derive(Debug, Default, Serialize)]
pub struct NotificationOutput {
    /// A system message to output regarding the notification.
    #[serde(skip_serializing_if = "Option::is_none")]
    pub system_message: Option<String>,
}

/// The response generated by a `PreCompress` hook.
#[derive(Debug, Default, Serialize)]
pub struct PreCompressOutput {
    /// A system message detailing the compression event.
    #[serde(skip_serializing_if = "Option::is_none")]
    pub system_message: Option<String>,
    /// The hook's decision on the compression.
    #[serde(skip_serializing_if = "Option::is_none")]
    pub decision: Option<Decision>,
    /// Reason for the decision.
    #[serde(skip_serializing_if = "Option::is_none")]
    pub reason: Option<String>,
    /// An exit code if the compression is halting the process.
    #[serde(skip_serializing_if = "Option::is_none")]
    pub exit_code: Option<i32>,
}

/// The response generated by a `CwdChanged` hook.
#[derive(Debug, Default, Serialize)]
pub struct CwdChangedOutput {
    /// Environment variables to persist for the new directory.
    #[serde(skip_serializing_if = "Option::is_none")]
    pub persist_env: Option<Value>,
    /// Paths to start watching due to the cwd change.
    #[serde(skip_serializing_if = "Option::is_none")]
    pub watch_paths: Option<Vec<String>>,
}

/// The response generated by a `FileChanged` hook.
#[derive(Debug, Default, Serialize)]
pub struct FileChangedOutput {
    /// Environment variables to update based on the file change.
    #[serde(skip_serializing_if = "Option::is_none")]
    pub persist_env: Option<Value>,
    /// Additional paths to start watching.
    #[serde(skip_serializing_if = "Option::is_none")]
    pub watch_paths: Option<Vec<String>>,
}

/// The response generated by an `InstructionsLoaded` hook.
#[derive(Debug, Default, Serialize)]
pub struct InstructionsLoadedOutput {
    /// A system message to display regarding the loaded instructions.
    #[serde(skip_serializing_if = "Option::is_none")]
    pub system_message: Option<String>,
}

/// The response generated by a `UserPromptSubmit` hook.
#[derive(Debug, Default, Serialize)]
pub struct UserPromptSubmitOutput {
    /// Additional context to append to the prompt.
    #[serde(skip_serializing_if = "Option::is_none")]
    pub additional_context: Option<String>,
    /// Decision on whether to process the prompt.
    #[serde(skip_serializing_if = "Option::is_none")]
    pub decision: Option<Decision>,
    /// Reason for the decision.
    #[serde(skip_serializing_if = "Option::is_none")]
    pub reason: Option<String>,
}

/// The response generated by a `WorktreeCreate` hook.
#[derive(Debug, Default, Serialize)]
pub struct WorktreeCreateOutput {
    /// The path to the created worktree, if modified by the hook.
    #[serde(skip_serializing_if = "Option::is_none")]
    pub worktree_path: Option<String>,
}

/// The response generated by a `WorktreeRemove` hook.
#[derive(Debug, Default, Serialize)]
pub struct WorktreeRemoveOutput {}

impl HookOutputEvent {
    /// Returns the exit code and reason associated with the hook output, if halting.
    ///
    /// # Examples
    ///
    /// ```
    /// use inceptool_protocols::{HookOutputEvent, BeforeToolOutput, Decision};
    ///
    /// let output = HookOutputEvent::BeforeTool(BeforeToolOutput {
    ///     decision: Some(Decision::Block),
    ///     exit_code: Some(1),
    ///     reason: Some("Not allowed".to_string()),
    ///     ..Default::default()
    /// });
    ///
    /// assert_eq!(output.exit_metadata(), (Some(1), Some("Not allowed")));
    /// ```
    pub fn exit_metadata(&self) -> (Option<i32>, Option<&str>) {
        match self {
            HookOutputEvent::BeforeTool(o) => (o.exit_code, o.reason.as_deref()),
            HookOutputEvent::AfterTool(o) => (o.exit_code, o.reason.as_deref()),
            HookOutputEvent::BeforeAgent(o) => (o.exit_code, o.reason.as_deref()),
            HookOutputEvent::AfterAgent(o) => (o.exit_code, o.reason.as_deref()),
            HookOutputEvent::BeforeModel(o) => (o.exit_code, o.reason.as_deref()),
            HookOutputEvent::AfterModel(o) => (o.exit_code, o.reason.as_deref()),
            HookOutputEvent::PreCompress(o) => (o.exit_code, o.reason.as_deref()),
            _ => (None, None),
        }
    }

    /// Returns the decision associated with the hook output, if any.
    pub fn decision(&self) -> Option<Decision> {
        match self {
            HookOutputEvent::BeforeTool(o) => o.decision,
            HookOutputEvent::AfterTool(o) => o.decision,
            HookOutputEvent::BeforeAgent(o) => o.decision,
            HookOutputEvent::AfterAgent(o) => o.decision,
            HookOutputEvent::BeforeModel(o) => o.decision,
            HookOutputEvent::AfterModel(o) => o.decision,
            HookOutputEvent::PreCompress(o) => o.decision,
            HookOutputEvent::UserPromptSubmit(o) => o.decision,
            _ => None,
        }
    }

    /// Returns the reason associated with the hook output, if any.
    pub fn reason(&self) -> Option<&str> {
        match self {
            HookOutputEvent::BeforeTool(o) => o.reason.as_deref(),
            HookOutputEvent::AfterTool(o) => o.reason.as_deref(),
            HookOutputEvent::BeforeAgent(o) => o.reason.as_deref(),
            HookOutputEvent::AfterAgent(o) => o.reason.as_deref(),
            HookOutputEvent::BeforeModel(o) => o.reason.as_deref(),
            HookOutputEvent::AfterModel(o) => o.reason.as_deref(),
            HookOutputEvent::PreCompress(o) => o.reason.as_deref(),
            HookOutputEvent::UserPromptSubmit(o) => o.reason.as_deref(),
            _ => None,
        }
    }

    /// Returns whether to halt the process entirely.
    pub fn halt(&self) -> Option<bool> {
        match self {
            HookOutputEvent::BeforeTool(o) => o.halt,
            HookOutputEvent::AfterTool(o) => o.halt,
            HookOutputEvent::BeforeAgent(o) => o.halt,
            HookOutputEvent::AfterAgent(o) => o.halt,
            HookOutputEvent::BeforeModel(o) => o.halt,
            HookOutputEvent::AfterModel(o) => o.halt,
            _ => None,
        }
    }

    /// Returns whether to suppress output.
    pub fn suppress_output(&self) -> Option<bool> {
        match self {
            HookOutputEvent::AfterTool(o) => o.suppress_output,
            _ => None,
        }
    }

    /// Returns the system message associated with the hook output, if any.
    pub fn system_message(&self) -> Option<&str> {
        match self {
            HookOutputEvent::SessionStart(o) => o.system_message.as_deref(),
            HookOutputEvent::SessionEnd(o) => o.system_message.as_deref(),
            HookOutputEvent::Notification(o) => o.system_message.as_deref(),
            HookOutputEvent::PreCompress(o) => o.system_message.as_deref(),
            HookOutputEvent::InstructionsLoaded(o) => o.system_message.as_deref(),
            _ => None,
        }
    }
}

#[cfg(test)]
mod tests {
    use super::*;

    use crate::error::ProtocolError;
    use crate::types::Decision;

    use rstest::{fixture, rstest};
    use serde_json::json;

    #[derive(thiserror::Error, Debug)]
    pub enum TestError {
        #[error(transparent)]
        Protocol(#[from] ProtocolError),
        #[error(transparent)]
        Json(#[from] serde_json::Error),
    }

    #[fixture]
    fn allow_decision() -> Decision {
        Decision::Allow
    }

    #[fixture]
    fn block_decision() -> Decision {
        Decision::Block
    }

    #[rstest]
    #[case(Some(42), Some("Access Denied".to_string()))]
    #[case(None, None)]
    #[case(Some(1), None)]
    fn test_exit_metadata_extraction(
        block_decision: Decision,
        #[case] code: Option<i32>,
        #[case] reason: Option<String>,
    ) -> Result<(), TestError> {
        let output = HookOutputEvent::BeforeTool(BeforeToolOutput {
            decision: Some(block_decision),
            reason: reason.clone(),
            exit_code: code,
            ..Default::default()
        });

        let (extracted_code, extracted_reason) = output.exit_metadata();

        assert_eq!(extracted_code, code);
        assert_eq!(extracted_reason, reason.as_deref());

        Ok(())
    }

    #[rstest]
    #[case::worktree_remove(HookOutputEvent::WorktreeRemove(WorktreeRemoveOutput {}))]
    #[case::notification(HookOutputEvent::Notification(NotificationOutput { system_message: Some("hello".into()) }))]
    fn test_exit_metadata_fallthrough(#[case] output: HookOutputEvent) -> Result<(), TestError> {
        let (code, reason) = output.exit_metadata();

        assert_eq!(code, None);
        assert_eq!(reason, None);

        Ok(())
    }

    #[rstest]
    fn test_untagged_hook_output_serialization(allow_decision: Decision) -> Result<(), TestError> {
        let output = HookOutputEvent::BeforeTool(BeforeToolOutput {
            decision: Some(allow_decision),
            additional_context: Some("Added context".to_string()),
            ..Default::default()
        });

        let serialized = serde_json::to_value(&output)?;

        assert_eq!(
            serialized,
            json!({
                "decision": "allow",
                "additional_context": "Added context"
            })
        );

        Ok(())
    }

    #[rstest]
    #[case::before_tool(HookOutputEvent::BeforeTool(BeforeToolOutput::default()))]
    #[case::after_tool(HookOutputEvent::AfterTool(AfterToolOutput::default()))]
    #[case::before_agent(HookOutputEvent::BeforeAgent(BeforeAgentOutput::default()))]
    #[case::after_agent(HookOutputEvent::AfterAgent(AfterAgentOutput::default()))]
    #[case::before_model(HookOutputEvent::BeforeModel(BeforeModelOutput::default()))]
    #[case::after_model(HookOutputEvent::AfterModel(AfterModelOutput::default()))]
    #[case::before_tool_selection(HookOutputEvent::BeforeToolSelection(
        BeforeToolSelectionOutput::default()
    ))]
    #[case::session_start(HookOutputEvent::SessionStart(SessionStartOutput::default()))]
    #[case::session_end(HookOutputEvent::SessionEnd(SessionEndOutput::default()))]
    #[case::notification(HookOutputEvent::Notification(NotificationOutput::default()))]
    #[case::pre_compress(HookOutputEvent::PreCompress(PreCompressOutput::default()))]
    #[case::cwd_changed(HookOutputEvent::CwdChanged(CwdChangedOutput::default()))]
    #[case::file_changed(HookOutputEvent::FileChanged(FileChangedOutput::default()))]
    #[case::instructions_loaded(HookOutputEvent::InstructionsLoaded(
        InstructionsLoadedOutput::default()
    ))]
    #[case::user_prompt_submit(HookOutputEvent::UserPromptSubmit(
        UserPromptSubmitOutput::default()
    ))]
    #[case::worktree_create(HookOutputEvent::WorktreeCreate(WorktreeCreateOutput::default()))]
    #[case::worktree_remove(HookOutputEvent::WorktreeRemove(WorktreeRemoveOutput::default()))]
    fn test_exhaustive_hook_output_serialization_empty(
        #[case] out: HookOutputEvent,
    ) -> Result<(), TestError> {
        let serialized = serde_json::to_value(&out)?;
        assert_eq!(serialized, json!({}));
        Ok(())
    }

    #[rstest]
    fn test_hook_output_serialization_populated() -> Result<(), TestError> {
        let out = HookOutputEvent::SessionStart(SessionStartOutput {
            system_message: Some("hello".to_string()),
            ..Default::default()
        });

        assert_eq!(
            serde_json::to_value(&out)?,
            json!({"system_message": "hello"})
        );

        Ok(())
    }

    #[rstest]
    #[case::before_tool(HookOutputEvent::BeforeTool(BeforeToolOutput { exit_code: Some(1), ..Default::default() }), 1)]
    #[case::after_tool(HookOutputEvent::AfterTool(AfterToolOutput { exit_code: Some(2), ..Default::default() }), 2)]
    #[case::before_agent(HookOutputEvent::BeforeAgent(BeforeAgentOutput { exit_code: Some(3), ..Default::default() }), 3)]
    #[case::after_agent(HookOutputEvent::AfterAgent(AfterAgentOutput { exit_code: Some(4), ..Default::default() }), 4)]
    #[case::before_model(HookOutputEvent::BeforeModel(BeforeModelOutput { exit_code: Some(5), ..Default::default() }), 5)]
    #[case::after_model(HookOutputEvent::AfterModel(AfterModelOutput { exit_code: Some(6), ..Default::default() }), 6)]
    #[case::pre_compress(HookOutputEvent::PreCompress(PreCompressOutput { exit_code: Some(7), ..Default::default() }), 7)]
    fn test_all_exit_metadata_arms(
        #[case] output: HookOutputEvent,
        #[case] expected_code: i32,
    ) -> Result<(), TestError> {
        let (code, _) = output.exit_metadata();
        assert_eq!(code, Some(expected_code));
        Ok(())
    }

    #[rstest]
    #[case::before_tool(HookOutputEvent::BeforeTool(BeforeToolOutput { decision: Some(Decision::Allow), ..Default::default() }), Some(Decision::Allow))]
    #[case::after_tool(HookOutputEvent::AfterTool(AfterToolOutput { decision: Some(Decision::Block), ..Default::default() }), Some(Decision::Block))]
    #[case::session_start_none(HookOutputEvent::SessionStart(SessionStartOutput::default()), None)]
    fn test_decision_accessor(
        #[case] output: HookOutputEvent,
        #[case] expected: Option<Decision>,
    ) -> Result<(), TestError> {
        assert_eq!(output.decision(), expected);
        Ok(())
    }

    #[rstest]
    #[case::before_tool(HookOutputEvent::BeforeTool(BeforeToolOutput { reason: Some("test".into()), ..Default::default() }), Some("test"))]
    #[case::after_tool(HookOutputEvent::AfterTool(AfterToolOutput { reason: Some("denied".into()), ..Default::default() }), Some("denied"))]
    #[case::session_start_none(HookOutputEvent::SessionStart(SessionStartOutput::default()), None)]
    fn test_reason_accessor(
        #[case] output: HookOutputEvent,
        #[case] expected: Option<&str>,
    ) -> Result<(), TestError> {
        assert_eq!(output.reason(), expected);
        Ok(())
    }

    #[rstest]
    #[case::before_tool(HookOutputEvent::BeforeTool(BeforeToolOutput { halt: Some(true), ..Default::default() }), Some(true))]
    #[case::after_tool(HookOutputEvent::AfterTool(AfterToolOutput { halt: Some(false), ..Default::default() }), Some(false))]
    #[case::session_start_none(HookOutputEvent::SessionStart(SessionStartOutput::default()), None)]
    fn test_halt_accessor(
        #[case] output: HookOutputEvent,
        #[case] expected: Option<bool>,
    ) -> Result<(), TestError> {
        assert_eq!(output.halt(), expected);
        Ok(())
    }

    #[rstest]
    #[case::after_tool(HookOutputEvent::AfterTool(AfterToolOutput { suppress_output: Some(true), ..Default::default() }), Some(true))]
    #[case::after_tool_none(HookOutputEvent::AfterTool(AfterToolOutput::default()), None)]
    #[case::before_tool_none(HookOutputEvent::BeforeTool(BeforeToolOutput::default()), None)]
    fn test_suppress_output_accessor(
        #[case] output: HookOutputEvent,
        #[case] expected: Option<bool>,
    ) -> Result<(), TestError> {
        assert_eq!(output.suppress_output(), expected);
        Ok(())
    }

    #[rstest]
    #[case::session_start(HookOutputEvent::SessionStart(SessionStartOutput { system_message: Some("hello".into()), ..Default::default() }), Some("hello"))]
    #[case::session_end(HookOutputEvent::SessionEnd(SessionEndOutput { system_message: Some("bye".into()) }), Some("bye"))]
    #[case::before_tool_none(HookOutputEvent::BeforeTool(BeforeToolOutput::default()), None)]
    fn test_system_message_accessor(
        #[case] output: HookOutputEvent,
        #[case] expected: Option<&str>,
    ) -> Result<(), TestError> {
        assert_eq!(output.system_message(), expected);
        Ok(())
    }
}
