//! Definitions for all output payloads returned by hooks.

use crate::types::{Decision, PermissionBehavior};

use serde::Serialize;
use serde_json::Value;
use std::borrow::Cow;

/// Represents the overall output from any hook.
///
/// This enum is untagged so it serializes directly into the underlying variant's structure.
#[derive(Debug, Serialize, strum_macros::AsRefStr, strum_macros::IntoStaticStr)]
#[serde(untagged)]
pub enum HookOutputEvent {
    /// Output for a `PreToolUse` event.
    PreToolUse(PreToolUseOutput),
    /// Output for a `PostToolUse` event.
    PostToolUse(PostToolUseOutput),
    /// Output for a `BeforeAgent` event.
    BeforeAgent(BeforeAgentOutput),
    /// Output for an `AfterAgent` event.
    AfterAgent(AfterAgentOutput),
    /// Output for a `BeforeModel` event.
    BeforeModel(BeforeModelOutput),
    /// Output for an `AfterModel` event.
    AfterModel(AfterModelOutput),
    /// Output for a `BeforeToolSelection` event.
    BeforeToolSelection(BeforeToolSelectionOutput),
    /// Output for a `SessionStart` event.
    SessionStart(SessionStartOutput),
    /// Output for a `SessionEnd` event.
    SessionEnd(SessionEndOutput),
    /// Output for a `Notification` event.
    Notification(NotificationOutput),
    /// Output for a `PreCompact` event.
    PreCompact(PreCompactOutput),
    /// Output for a `CwdChanged` event.
    CwdChanged(CwdChangedOutput),
    /// Output for a `FileChanged` event.
    FileChanged(FileChangedOutput),
    /// Output for an `InstructionsLoaded` event.
    InstructionsLoaded(InstructionsLoadedOutput),
    /// Output for a `UserPromptSubmit` event.
    UserPromptSubmit(UserPromptSubmitOutput),
    /// Output for a `WorktreeCreate` event.
    WorktreeCreate(WorktreeCreateOutput),
    /// Output for a `WorktreeRemove` event.
    WorktreeRemove(EmptyOutput),
    /// Output for a `Setup` event. Fires only on explicit setup/initialization.
    Setup(SetupOutput),
    /// Output for a `UserPromptExpansion` event. Runs when a slash command expands.
    UserPromptExpansion(UserPromptExpansionOutput),
    /// Output for a `MessageDisplay` event. Runs when a message incrementally displays.
    MessageDisplay(MessageDisplayOutput),
    /// Output for a `PermissionRequest` event. Runs when a permission dialog is shown.
    PermissionRequest(PermissionRequestOutput),
    /// Output for a `PostToolUseFailure` event. Runs when a tool throws an error or fails.
    PostToolUseFailure(PostToolUseFailureOutput),
    /// Output for a `PostToolBatch` event. Runs once after a batch of tools resolves.
    PostToolBatch(PostToolBatchOutput),
    /// Output for a `PermissionDenied` event. Runs when the auto classifier denies a tool.
    PermissionDenied(PermissionDeniedOutput),
    /// Output for a `SubagentStart` event. Runs when a subagent is spawned.
    SubagentStart(SubagentStartOutput),
    /// Output for a `SubagentStop` event. Runs when a subagent finishes.
    SubagentStop(SubagentStopOutput),
    /// Output for a `TaskCreated` event. Runs when a background task is created.
    TaskCreated(TaskCreatedOutput),
    /// Output for a `TaskCompleted` event. Runs when a task is marked as completed.
    TaskCompleted(TaskCompletedOutput),
    /// Output for a `Stop` event. Runs when the main agent finishes responding.
    Stop(StopOutput),
    /// Output for a `StopFailure` event. Runs when a turn ends due to an API error.
    StopFailure(EmptyOutput),
    /// Output for a `TeammateIdle` event. Runs when a teammate is about to go idle.
    TeammateIdle(TeammateIdleOutput),
    /// Output for a `ConfigChange` event. Runs when a configuration file changes.
    ConfigChange(ConfigChangeOutput),
    /// Output for a `PostCompact` event. Runs after a compact operation finishes.
    PostCompact(PostCompactOutput),
    /// Output for a `Elicitation` event. Runs when an MCP server requests user input.
    Elicitation(ElicitationOutput),
    /// Output for a `ElicitationResult` event. Runs when an elicitation result is received.
    ElicitationResult(EmptyOutput),
}

/// The response generated by a `PreToolUse` hook.
///
/// Returns decisions to allow, block, or modify the execution of a tool.
#[derive(Debug, Default, Serialize)]
pub struct PreToolUseOutput {
    /// The hook's decision on whether to allow the tool execution.
    #[serde(skip_serializing_if = "Option::is_none")]
    pub decision: Option<Decision>,
    /// The reason for the decision, if any.
    #[serde(skip_serializing_if = "Option::is_none")]
    pub reason: Option<Cow<'static, str>>,
    /// Overridden input arguments for the tool.
    #[serde(skip_serializing_if = "Option::is_none")]
    pub updated_input: Option<Value>,
    /// Additional context injected into the prompt.
    #[serde(skip_serializing_if = "Option::is_none")]
    pub additional_context: Option<Cow<'static, str>>,
    /// Indicates whether to halt the process entirely.
    #[serde(skip_serializing_if = "Option::is_none")]
    pub halt: Option<bool>,
    /// An exit code to return if halting.
    #[serde(skip_serializing_if = "Option::is_none")]
    pub exit_code: Option<i32>,
}

/// The response generated by a `PostToolUse` hook.
///
/// Returns decisions on how to handle the tool's result, optionally suppressing or updating the output.
#[derive(Debug, Default, Serialize)]
pub struct PostToolUseOutput {
    /// The hook's decision based on the tool's output.
    #[serde(skip_serializing_if = "Option::is_none")]
    pub decision: Option<Decision>,
    /// The reason for the decision, if any.
    #[serde(skip_serializing_if = "Option::is_none")]
    pub reason: Option<Cow<'static, str>>,
    /// Additional context injected into the prompt.
    #[serde(skip_serializing_if = "Option::is_none")]
    pub additional_context: Option<Cow<'static, str>>,
    /// Overridden output returned to the model.
    #[serde(skip_serializing_if = "Option::is_none")]
    pub updated_tool_output: Option<Value>,
    /// If true, suppresses the tool's actual output from the model.
    #[serde(skip_serializing_if = "Option::is_none")]
    pub suppress_output: Option<bool>,
    /// Indicates whether to halt the process entirely.
    #[serde(skip_serializing_if = "Option::is_none")]
    pub halt: Option<bool>,
    /// An exit code to return if halting.
    #[serde(skip_serializing_if = "Option::is_none")]
    pub exit_code: Option<i32>,
}

/// The response generated by a `BeforeAgent` hook.
///
/// Returns instructions or decisions before an agent starts working on a prompt.
#[derive(Debug, Default, Serialize)]
pub struct BeforeAgentOutput {
    /// The hook's decision on whether to allow the agent to start.
    #[serde(skip_serializing_if = "Option::is_none")]
    pub decision: Option<Decision>,
    /// The reason for the decision, if any.
    #[serde(skip_serializing_if = "Option::is_none")]
    pub reason: Option<Cow<'static, str>>,
    /// Additional context to inject before the agent starts.
    #[serde(skip_serializing_if = "Option::is_none")]
    pub additional_context: Option<Cow<'static, str>>,
    /// Indicates whether to halt the process entirely.
    #[serde(skip_serializing_if = "Option::is_none")]
    pub halt: Option<bool>,
    /// An exit code to return if halting.
    #[serde(skip_serializing_if = "Option::is_none")]
    pub exit_code: Option<i32>,
}

/// The response generated by an `AfterAgent` hook.
///
/// Returns instructions or decisions on how to handle the final result from the agent.
#[derive(Debug, Default, Serialize)]
pub struct AfterAgentOutput {
    /// The hook's decision based on the agent's run.
    #[serde(skip_serializing_if = "Option::is_none")]
    pub decision: Option<Decision>,
    /// The reason for the decision, if any.
    #[serde(skip_serializing_if = "Option::is_none")]
    pub reason: Option<Cow<'static, str>>,
    /// Indicates if the context should be cleared.
    #[serde(skip_serializing_if = "Option::is_none")]
    pub clear_context: Option<bool>,
    /// Indicates whether to halt the process entirely.
    #[serde(skip_serializing_if = "Option::is_none")]
    pub halt: Option<bool>,
    /// An exit code to return if halting.
    #[serde(skip_serializing_if = "Option::is_none")]
    pub exit_code: Option<i32>,
}

/// The response generated by a `BeforeModel` hook.
///
/// Returns overrides or blocks for raw LLM requests before hitting the model API.
#[derive(Debug, Default, Serialize)]
pub struct BeforeModelOutput {
    /// The hook's decision on whether to proceed with the model request.
    #[serde(skip_serializing_if = "Option::is_none")]
    pub decision: Option<Decision>,
    /// The reason for the decision.
    #[serde(skip_serializing_if = "Option::is_none")]
    pub reason: Option<Cow<'static, str>>,
    /// A modified LLM request to use instead of the original.
    #[serde(skip_serializing_if = "Option::is_none")]
    pub llm_request: Option<Value>,
    /// A stubbed LLM response to return immediately without calling the API.
    #[serde(skip_serializing_if = "Option::is_none")]
    pub llm_response: Option<Value>,
    /// Indicates whether to halt the process entirely.
    #[serde(skip_serializing_if = "Option::is_none")]
    pub halt: Option<bool>,
    /// An exit code to return if halting.
    #[serde(skip_serializing_if = "Option::is_none")]
    pub exit_code: Option<i32>,
}

/// The response generated by an `AfterModel` hook.
///
/// Returns overrides or decisions based on raw LLM responses.
#[derive(Debug, Default, Serialize)]
pub struct AfterModelOutput {
    /// The hook's decision on how to handle the model's response.
    #[serde(skip_serializing_if = "Option::is_none")]
    pub decision: Option<Decision>,
    /// The reason for the decision.
    #[serde(skip_serializing_if = "Option::is_none")]
    pub reason: Option<Cow<'static, str>>,
    /// A modified LLM response to use instead of the original.
    #[serde(skip_serializing_if = "Option::is_none")]
    pub llm_response: Option<Value>,
    /// Indicates whether to halt the process entirely.
    #[serde(skip_serializing_if = "Option::is_none")]
    pub halt: Option<bool>,
    /// An exit code to return if halting.
    #[serde(skip_serializing_if = "Option::is_none")]
    pub exit_code: Option<i32>,
}

/// The response generated by a `BeforeToolSelection` hook.
///
/// Returns modifications to the tool configurations exposed to the model.
#[derive(Debug, Default, Serialize)]
pub struct BeforeToolSelectionOutput {
    /// Modified tool configurations to provide to the model.
    #[serde(skip_serializing_if = "Option::is_none")]
    pub tool_config: Option<Value>,
}

/// The response generated by a `SessionStart` hook.
///
/// Returns persisted environments, system messages, or context for the new session.
#[derive(Debug, Default, Serialize)]
pub struct SessionStartOutput {
    /// Additional context to start the session with.
    #[serde(skip_serializing_if = "Option::is_none")]
    pub additional_context: Option<Cow<'static, str>>,
    /// A system message to output to the user.
    #[serde(skip_serializing_if = "Option::is_none")]
    pub system_message: Option<String>,
    /// Environment variables to persist.
    #[serde(skip_serializing_if = "Option::is_none")]
    pub persist_env: Option<Value>,
    /// An initial user message to seed the new session with.
    #[serde(skip_serializing_if = "Option::is_none")]
    pub initial_user_message: Option<String>,
    /// A title to assign to the new session.
    #[serde(skip_serializing_if = "Option::is_none")]
    pub session_title: Option<String>,
    /// Additional paths to watch for the duration of the session.
    #[serde(skip_serializing_if = "Option::is_none")]
    pub watch_paths: Option<Vec<String>>,
    /// Whether to reload skills for the new session.
    #[serde(skip_serializing_if = "Option::is_none")]
    pub reload_skills: Option<bool>,
}

/// The response generated by a `SessionEnd` hook.
///
/// Returns an optional final system message to display before the session closes.
#[derive(Debug, Default, Serialize)]
pub struct SessionEndOutput {
    /// A final system message to output to the user.
    #[serde(skip_serializing_if = "Option::is_none")]
    pub system_message: Option<String>,
}

/// The response generated by a `Notification` hook.
///
/// Returns an optional system message to display as a reaction to a notification.
#[derive(Debug, Default, Serialize)]
pub struct NotificationOutput {
    /// A system message to output regarding the notification.
    #[serde(skip_serializing_if = "Option::is_none")]
    pub system_message: Option<String>,
}

/// The response generated by a `PreCompact` hook.
///
/// Returns decisions on context compression or messages to log when compression occurs.
#[derive(Debug, Default, Serialize)]
pub struct PreCompactOutput {
    /// A system message detailing the compression event.
    #[serde(skip_serializing_if = "Option::is_none")]
    pub system_message: Option<String>,
    /// The hook's decision on the compression.
    #[serde(skip_serializing_if = "Option::is_none")]
    pub decision: Option<Decision>,
    /// Reason for the decision.
    #[serde(skip_serializing_if = "Option::is_none")]
    pub reason: Option<Cow<'static, str>>,
    /// An exit code if the compression is halting the process.
    #[serde(skip_serializing_if = "Option::is_none")]
    pub exit_code: Option<i32>,
}

/// The response generated by a `CwdChanged` hook.
///
/// Returns environment variable updates or directories to watch based on the new working directory.
#[derive(Debug, Default, Serialize)]
pub struct CwdChangedOutput {
    /// Environment variables to persist for the new directory.
    #[serde(skip_serializing_if = "Option::is_none")]
    pub persist_env: Option<Value>,
    /// Paths to start watching due to the cwd change.
    #[serde(skip_serializing_if = "Option::is_none")]
    pub watch_paths: Option<Vec<String>>,
}

/// The response generated by a `FileChanged` hook.
///
/// Returns environment variables to update or new file paths to watch.
#[derive(Debug, Default, Serialize)]
pub struct FileChangedOutput {
    /// Environment variables to update based on the file change.
    #[serde(skip_serializing_if = "Option::is_none")]
    pub persist_env: Option<Value>,
    /// Additional paths to start watching.
    #[serde(skip_serializing_if = "Option::is_none")]
    pub watch_paths: Option<Vec<String>>,
}

/// The response generated by an `InstructionsLoaded` hook.
///
/// Returns a system message to display upon successfully loading instructions.
#[derive(Debug, Default, Serialize)]
pub struct InstructionsLoadedOutput {
    /// A system message to display regarding the loaded instructions.
    #[serde(skip_serializing_if = "Option::is_none")]
    pub system_message: Option<String>,
}

/// The response generated by a `UserPromptSubmit` hook.
///
/// Returns a decision on the prompt, or additional context to append to it.
#[derive(Debug, Default, Serialize)]
pub struct UserPromptSubmitOutput {
    /// Additional context to append to the prompt.
    #[serde(skip_serializing_if = "Option::is_none")]
    pub additional_context: Option<Cow<'static, str>>,
    /// Decision on whether to process the prompt.
    #[serde(skip_serializing_if = "Option::is_none")]
    pub decision: Option<Decision>,
    /// Reason for the decision.
    #[serde(skip_serializing_if = "Option::is_none")]
    pub reason: Option<Cow<'static, str>>,
}

/// The response generated by a `WorktreeCreate` hook.
///
/// Returns a modified worktree path, if the hook desires to change the creation path.
#[derive(Debug, Default, Serialize)]
pub struct WorktreeCreateOutput {
    /// The path to the created worktree, if modified by the hook.
    #[serde(skip_serializing_if = "Option::is_none")]
    pub worktree_path: Option<String>,
}

/// The response generated by a `Setup` hook.
///
/// Returns additional context to inject during setup/initialization.
#[derive(Debug, Default, Serialize)]
pub struct SetupOutput {
    /// Additional context to inject during setup.
    #[serde(skip_serializing_if = "Option::is_none")]
    pub additional_context: Option<Cow<'static, str>>,
}

/// The response generated by a `UserPromptExpansion` hook.
///
/// Returns a decision on the expansion, or additional context to append.
#[derive(Debug, Default, Serialize)]
pub struct UserPromptExpansionOutput {
    /// The hook's decision on whether to allow the expansion.
    #[serde(skip_serializing_if = "Option::is_none")]
    pub decision: Option<Decision>,
    /// The reason for the decision, if any.
    #[serde(skip_serializing_if = "Option::is_none")]
    pub reason: Option<Cow<'static, str>>,
    /// Additional context to append as a result of the expansion.
    #[serde(skip_serializing_if = "Option::is_none")]
    pub additional_context: Option<Cow<'static, str>>,
}

/// The response generated by a `MessageDisplay` hook.
///
/// Returns replacement text for the displayed message.
#[derive(Debug, Default, Serialize)]
pub struct MessageDisplayOutput {
    /// Replacement text for the displayed message.
    #[serde(skip_serializing_if = "Option::is_none")]
    pub replacement_text: Option<String>,
}

/// The response generated by a `PermissionRequest` hook.
///
/// Returns a decision on the permission request, optionally overriding the
/// tool input or the matching permission rule.
#[derive(Debug, Default, Serialize)]
pub struct PermissionRequestOutput {
    /// The behavior to apply to the permission request.
    #[serde(skip_serializing_if = "Option::is_none")]
    pub behavior: Option<PermissionBehavior>,
    /// Overridden input arguments for the tool.
    #[serde(skip_serializing_if = "Option::is_none")]
    pub updated_input: Option<Value>,
    /// An overridden permission rule definition to apply.
    #[serde(skip_serializing_if = "Option::is_none")]
    pub permission_rule_definition: Option<Value>,
}

/// The response generated by a `PostToolUseFailure` hook.
///
/// Returns a decision on how to handle a tool that threw an error or failed.
#[derive(Debug, Default, Serialize)]
pub struct PostToolUseFailureOutput {
    /// The hook's decision based on the tool failure.
    #[serde(skip_serializing_if = "Option::is_none")]
    pub decision: Option<Decision>,
    /// The reason for the decision, if any.
    #[serde(skip_serializing_if = "Option::is_none")]
    pub reason: Option<Cow<'static, str>>,
}

/// The response generated by a `PostToolBatch` hook.
///
/// Returns a decision on how to handle the resolved batch of tool calls.
#[derive(Debug, Default, Serialize)]
pub struct PostToolBatchOutput {
    /// The hook's decision based on the resolved batch.
    #[serde(skip_serializing_if = "Option::is_none")]
    pub decision: Option<Decision>,
    /// The reason for the decision, if any.
    #[serde(skip_serializing_if = "Option::is_none")]
    pub reason: Option<Cow<'static, str>>,
}

/// The response generated by a `PermissionDenied` hook.
///
/// Returns additional context to inject after the auto classifier denies a tool.
#[derive(Debug, Default, Serialize)]
pub struct PermissionDeniedOutput {
    /// Additional context to inject after the denial.
    #[serde(skip_serializing_if = "Option::is_none")]
    pub additional_context: Option<Cow<'static, str>>,
}

/// The response generated by a `SubagentStart` hook.
///
/// Returns additional context to inject when a subagent is spawned.
#[derive(Debug, Default, Serialize)]
pub struct SubagentStartOutput {
    /// Additional context to inject for the spawned subagent.
    #[serde(skip_serializing_if = "Option::is_none")]
    pub additional_context: Option<Cow<'static, str>>,
}

/// The response generated by a `SubagentStop` hook.
///
/// Returns a decision on how to handle a finished subagent.
#[derive(Debug, Default, Serialize)]
pub struct SubagentStopOutput {
    /// The hook's decision based on the subagent's run.
    #[serde(skip_serializing_if = "Option::is_none")]
    pub decision: Option<Decision>,
    /// The reason for the decision, if any.
    #[serde(skip_serializing_if = "Option::is_none")]
    pub reason: Option<Cow<'static, str>>,
    /// Additional context to inject as a result of the subagent's run.
    #[serde(skip_serializing_if = "Option::is_none")]
    pub additional_context: Option<Cow<'static, str>>,
}

/// The response generated by a `TaskCreated` hook.
///
/// Returns a decision on whether to allow the background task creation.
#[derive(Debug, Default, Serialize)]
pub struct TaskCreatedOutput {
    /// The hook's decision on whether to allow the task creation.
    #[serde(skip_serializing_if = "Option::is_none")]
    pub decision: Option<Decision>,
    /// The reason for the decision, if any.
    #[serde(skip_serializing_if = "Option::is_none")]
    pub reason: Option<Cow<'static, str>>,
}

/// The response generated by a `TaskCompleted` hook.
///
/// Returns a decision on how to handle a task marked as completed.
#[derive(Debug, Default, Serialize)]
pub struct TaskCompletedOutput {
    /// The hook's decision based on the completed task.
    #[serde(skip_serializing_if = "Option::is_none")]
    pub decision: Option<Decision>,
    /// The reason for the decision, if any.
    #[serde(skip_serializing_if = "Option::is_none")]
    pub reason: Option<Cow<'static, str>>,
}

/// The response generated by a `Stop` hook.
///
/// Returns a decision on whether the agent may stop responding, plus any
/// additional context to continue with.
#[derive(Debug, Default, Serialize)]
pub struct StopOutput {
    /// The hook's decision on whether the agent may stop.
    #[serde(skip_serializing_if = "Option::is_none")]
    pub decision: Option<Decision>,
    /// Additional context to continue with if the agent does not stop.
    #[serde(skip_serializing_if = "Option::is_none")]
    pub additional_context: Option<Cow<'static, str>>,
}

/// The response generated by a `TeammateIdle` hook.
///
/// Returns a decision on whether the teammate may go idle.
#[derive(Debug, Default, Serialize)]
pub struct TeammateIdleOutput {
    /// The hook's decision on whether the teammate may go idle.
    #[serde(skip_serializing_if = "Option::is_none")]
    pub decision: Option<Decision>,
    /// The reason for the decision, if any.
    #[serde(skip_serializing_if = "Option::is_none")]
    pub reason: Option<Cow<'static, str>>,
}

/// The response generated by a `ConfigChange` hook.
///
/// Returns a decision on whether to allow the configuration change to take effect.
#[derive(Debug, Default, Serialize)]
pub struct ConfigChangeOutput {
    /// The hook's decision on whether to allow the configuration change.
    #[serde(skip_serializing_if = "Option::is_none")]
    pub decision: Option<Decision>,
    /// The reason for the decision, if any.
    #[serde(skip_serializing_if = "Option::is_none")]
    pub reason: Option<Cow<'static, str>>,
}

/// The response generated by a `PostCompact` hook.
///
/// Returns a system message to display after a compact operation finishes.
#[derive(Debug, Default, Serialize)]
pub struct PostCompactOutput {
    /// A system message to output regarding the compaction.
    #[serde(skip_serializing_if = "Option::is_none")]
    pub system_message: Option<String>,
}

/// The response generated by an `Elicitation` hook.
///
/// Returns a response to send back for the MCP server's elicitation request.
#[derive(Debug, Default, Serialize)]
pub struct ElicitationOutput {
    /// The response to send back to the MCP server.
    #[serde(skip_serializing_if = "Option::is_none")]
    pub response: Option<Value>,
}

/// A generic empty hook output for events that do not process return fields.
#[derive(Debug, Default, Serialize)]
pub struct EmptyOutput {}

impl HookOutputEvent {
    /// Returns the `(exit_code, reason)` pair for variants that can halt the
    /// process with a specific exit code ([`HookOutputEvent::PreToolUse`],
    /// [`HookOutputEvent::PostToolUse`], [`HookOutputEvent::BeforeAgent`],
    /// [`HookOutputEvent::AfterAgent`], [`HookOutputEvent::BeforeModel`],
    /// [`HookOutputEvent::AfterModel`], [`HookOutputEvent::PreCompact`]).
    /// All other variants return `(None, None)`.
    ///
    /// # Examples
    ///
    /// ```
    /// use inceptool_protocol::{HookOutputEvent, PreToolUseOutput, Decision};
    ///
    /// let output = HookOutputEvent::PreToolUse(PreToolUseOutput {
    ///     decision: Some(Decision::Block),
    ///     exit_code: Some(1),
    ///     reason: Some("Not allowed".into()),
    ///     ..Default::default()
    /// });
    ///
    /// assert_eq!(output.exit_metadata(), (Some(1), Some("Not allowed")));
    /// ```
    pub fn exit_metadata(&self) -> (Option<i32>, Option<&str>) {
        match self {
            HookOutputEvent::PreToolUse(o) => (o.exit_code, o.reason.as_deref()),
            HookOutputEvent::PostToolUse(o) => (o.exit_code, o.reason.as_deref()),
            HookOutputEvent::BeforeAgent(o) => (o.exit_code, o.reason.as_deref()),
            HookOutputEvent::AfterAgent(o) => (o.exit_code, o.reason.as_deref()),
            HookOutputEvent::BeforeModel(o) => (o.exit_code, o.reason.as_deref()),
            HookOutputEvent::AfterModel(o) => (o.exit_code, o.reason.as_deref()),
            HookOutputEvent::PreCompact(o) => (o.exit_code, o.reason.as_deref()),
            _ => (None, None),
        }
    }

    /// Returns the decision associated with the hook output, if any.
    ///
    /// See [`HookOutputEvent::set_decision`] for the full list of variants
    /// that carry a `decision` field; all other variants return `None`.
    pub const fn decision(&self) -> Option<Decision> {
        match self {
            HookOutputEvent::PreToolUse(o) => o.decision,
            HookOutputEvent::PostToolUse(o) => o.decision,
            HookOutputEvent::BeforeAgent(o) => o.decision,
            HookOutputEvent::AfterAgent(o) => o.decision,
            HookOutputEvent::BeforeModel(o) => o.decision,
            HookOutputEvent::AfterModel(o) => o.decision,
            HookOutputEvent::PreCompact(o) => o.decision,
            HookOutputEvent::UserPromptSubmit(o) => o.decision,
            HookOutputEvent::PostToolUseFailure(o) => o.decision,
            HookOutputEvent::PostToolBatch(o) => o.decision,
            HookOutputEvent::ConfigChange(o) => o.decision,
            HookOutputEvent::Stop(o) => o.decision,
            HookOutputEvent::UserPromptExpansion(o) => o.decision,
            HookOutputEvent::SubagentStop(o) => o.decision,
            HookOutputEvent::TaskCreated(o) => o.decision,
            HookOutputEvent::TaskCompleted(o) => o.decision,
            HookOutputEvent::TeammateIdle(o) => o.decision,
            _ => None,
        }
    }

    /// Overwrites the decision on the hook output, if the variant carries a [`Decision`].
    ///
    /// Variants without a `decision` field (e.g. [`HookOutputEvent::SessionStart`] or
    /// [`HookOutputEvent::PermissionRequest`], which conveys its outcome via `behavior`
    /// instead) are left unchanged.
    pub const fn set_decision(&mut self, decision: Decision) {
        match self {
            HookOutputEvent::PreToolUse(o) => o.decision = Some(decision),
            HookOutputEvent::PostToolUse(o) => o.decision = Some(decision),
            HookOutputEvent::BeforeAgent(o) => o.decision = Some(decision),
            HookOutputEvent::AfterAgent(o) => o.decision = Some(decision),
            HookOutputEvent::BeforeModel(o) => o.decision = Some(decision),
            HookOutputEvent::AfterModel(o) => o.decision = Some(decision),
            HookOutputEvent::PreCompact(o) => o.decision = Some(decision),
            HookOutputEvent::UserPromptSubmit(o) => o.decision = Some(decision),
            HookOutputEvent::PostToolUseFailure(o) => o.decision = Some(decision),
            HookOutputEvent::PostToolBatch(o) => o.decision = Some(decision),
            HookOutputEvent::ConfigChange(o) => o.decision = Some(decision),
            HookOutputEvent::Stop(o) => o.decision = Some(decision),
            HookOutputEvent::UserPromptExpansion(o) => o.decision = Some(decision),
            HookOutputEvent::SubagentStop(o) => o.decision = Some(decision),
            HookOutputEvent::TaskCreated(o) => o.decision = Some(decision),
            HookOutputEvent::TaskCompleted(o) => o.decision = Some(decision),
            HookOutputEvent::TeammateIdle(o) => o.decision = Some(decision),
            _ => {}
        }
    }

    /// Returns the reason associated with the hook output's decision, if any.
    ///
    /// Mirrors [`HookOutputEvent::decision`]'s variant coverage, except
    /// [`HookOutputEvent::Stop`] (whose output has no `reason` field).
    pub fn reason(&self) -> Option<&str> {
        match self {
            HookOutputEvent::PreToolUse(o) => o.reason.as_deref(),
            HookOutputEvent::PostToolUse(o) => o.reason.as_deref(),
            HookOutputEvent::BeforeAgent(o) => o.reason.as_deref(),
            HookOutputEvent::AfterAgent(o) => o.reason.as_deref(),
            HookOutputEvent::BeforeModel(o) => o.reason.as_deref(),
            HookOutputEvent::AfterModel(o) => o.reason.as_deref(),
            HookOutputEvent::PreCompact(o) => o.reason.as_deref(),
            HookOutputEvent::UserPromptSubmit(o) => o.reason.as_deref(),
            HookOutputEvent::PostToolUseFailure(o) => o.reason.as_deref(),
            HookOutputEvent::PostToolBatch(o) => o.reason.as_deref(),
            HookOutputEvent::ConfigChange(o) => o.reason.as_deref(),
            HookOutputEvent::UserPromptExpansion(o) => o.reason.as_deref(),
            HookOutputEvent::SubagentStop(o) => o.reason.as_deref(),
            HookOutputEvent::TaskCreated(o) => o.reason.as_deref(),
            HookOutputEvent::TaskCompleted(o) => o.reason.as_deref(),
            HookOutputEvent::TeammateIdle(o) => o.reason.as_deref(),
            _ => None,
        }
    }

    /// Returns whether the hook is requesting the process halt entirely.
    ///
    /// Only [`HookOutputEvent::PreToolUse`], [`HookOutputEvent::PostToolUse`],
    /// [`HookOutputEvent::BeforeAgent`], [`HookOutputEvent::AfterAgent`],
    /// [`HookOutputEvent::BeforeModel`], and [`HookOutputEvent::AfterModel`]
    /// carry a `halt` field; all other variants return `None`.
    pub const fn halt(&self) -> Option<bool> {
        match self {
            HookOutputEvent::PreToolUse(o) => o.halt,
            HookOutputEvent::PostToolUse(o) => o.halt,
            HookOutputEvent::BeforeAgent(o) => o.halt,
            HookOutputEvent::AfterAgent(o) => o.halt,
            HookOutputEvent::BeforeModel(o) => o.halt,
            HookOutputEvent::AfterModel(o) => o.halt,
            _ => None,
        }
    }

    /// Returns whether to suppress the tool's output from the model.
    ///
    /// Only [`HookOutputEvent::PostToolUse`] carries a `suppress_output`
    /// field; all other variants return `None`.
    pub const fn suppress_output(&self) -> Option<bool> {
        match self {
            HookOutputEvent::PostToolUse(o) => o.suppress_output,
            _ => None,
        }
    }

    /// Returns the system message associated with the hook output, if any.
    ///
    /// Only [`HookOutputEvent::SessionStart`], [`HookOutputEvent::SessionEnd`],
    /// [`HookOutputEvent::Notification`], [`HookOutputEvent::PreCompact`],
    /// [`HookOutputEvent::InstructionsLoaded`], and
    /// [`HookOutputEvent::PostCompact`] carry a `system_message` field; all
    /// other variants return `None`.
    pub fn system_message(&self) -> Option<&str> {
        match self {
            HookOutputEvent::SessionStart(o) => o.system_message.as_deref(),
            HookOutputEvent::SessionEnd(o) => o.system_message.as_deref(),
            HookOutputEvent::Notification(o) => o.system_message.as_deref(),
            HookOutputEvent::PreCompact(o) => o.system_message.as_deref(),
            HookOutputEvent::InstructionsLoaded(o) => o.system_message.as_deref(),
            HookOutputEvent::PostCompact(o) => o.system_message.as_deref(),
            _ => None,
        }
    }
}

#[cfg(test)]
mod tests {
    use super::*;

    use crate::error::ProtocolError;
    use crate::types::Decision;

    use rstest::{fixture, rstest};
    use serde_json::json;

    #[derive(thiserror::Error, Debug)]
    pub enum TestError {
        #[error(transparent)]
        Protocol(#[from] ProtocolError),
        #[error(transparent)]
        Json(#[from] serde_json::Error),
    }

    #[fixture]
    fn allow_decision() -> Decision {
        Decision::Allow
    }

    #[fixture]
    fn block_decision() -> Decision {
        Decision::Block
    }

    #[rstest]
    #[case(Some(42), Some("Access Denied".into()))]
    #[case(None, None)]
    #[case(Some(1), None)]
    fn test_exit_metadata_extraction(
        block_decision: Decision,
        #[case] code: Option<i32>,
        #[case] reason: Option<Cow<'static, str>>,
    ) -> Result<(), TestError> {
        let output = HookOutputEvent::PreToolUse(PreToolUseOutput {
            decision: Some(block_decision),
            reason: reason.clone(),
            exit_code: code,
            ..Default::default()
        });

        let (extracted_code, extracted_reason) = output.exit_metadata();

        assert_eq!(extracted_code, code);
        assert_eq!(extracted_reason, reason.as_deref());

        Ok(())
    }

    #[rstest]
    #[case::worktree_remove(HookOutputEvent::WorktreeRemove(EmptyOutput { }))]
    #[case::notification(HookOutputEvent::Notification(NotificationOutput { system_message: Some("hello".into()) }))]
    fn test_exit_metadata_fallthrough(#[case] output: HookOutputEvent) -> Result<(), TestError> {
        let (code, reason) = output.exit_metadata();

        assert_eq!(code, None);
        assert_eq!(reason, None);

        Ok(())
    }

    #[rstest]
    fn test_untagged_hook_output_serialization(allow_decision: Decision) -> Result<(), TestError> {
        let output = HookOutputEvent::PreToolUse(PreToolUseOutput {
            decision: Some(allow_decision),
            additional_context: Some("Added context".into()),
            ..Default::default()
        });

        let serialized = serde_json::to_value(&output)?;

        assert_eq!(
            serialized,
            json!({
                "decision": "allow",
                "additional_context": "Added context"
            })
        );

        Ok(())
    }

    #[rstest]
    #[case::pre_tool_use(HookOutputEvent::PreToolUse(PreToolUseOutput::default()))]
    #[case::post_tool_use(HookOutputEvent::PostToolUse(PostToolUseOutput::default()))]
    #[case::before_agent(HookOutputEvent::BeforeAgent(BeforeAgentOutput::default()))]
    #[case::after_agent(HookOutputEvent::AfterAgent(AfterAgentOutput::default()))]
    #[case::before_model(HookOutputEvent::BeforeModel(BeforeModelOutput::default()))]
    #[case::after_model(HookOutputEvent::AfterModel(AfterModelOutput::default()))]
    #[case::before_tool_selection(HookOutputEvent::BeforeToolSelection(
        BeforeToolSelectionOutput::default()
    ))]
    #[case::session_start(HookOutputEvent::SessionStart(SessionStartOutput::default()))]
    #[case::session_end(HookOutputEvent::SessionEnd(SessionEndOutput::default()))]
    #[case::notification(HookOutputEvent::Notification(NotificationOutput::default()))]
    #[case::pre_compact(HookOutputEvent::PreCompact(PreCompactOutput::default()))]
    #[case::cwd_changed(HookOutputEvent::CwdChanged(CwdChangedOutput::default()))]
    #[case::file_changed(HookOutputEvent::FileChanged(FileChangedOutput::default()))]
    #[case::instructions_loaded(HookOutputEvent::InstructionsLoaded(
        InstructionsLoadedOutput::default()
    ))]
    #[case::user_prompt_submit(HookOutputEvent::UserPromptSubmit(
        UserPromptSubmitOutput::default()
    ))]
    #[case::worktree_create(HookOutputEvent::WorktreeCreate(WorktreeCreateOutput::default()))]
    #[case::worktree_remove(HookOutputEvent::WorktreeRemove(EmptyOutput::default()))]
    #[case::setup(HookOutputEvent::Setup(SetupOutput::default()))]
    #[case::user_prompt_expansion(HookOutputEvent::UserPromptExpansion(
        UserPromptExpansionOutput::default()
    ))]
    #[case::message_display(HookOutputEvent::MessageDisplay(MessageDisplayOutput::default()))]
    #[case::permission_request(HookOutputEvent::PermissionRequest(
        PermissionRequestOutput::default()
    ))]
    #[case::post_tool_use_failure(HookOutputEvent::PostToolUseFailure(
        PostToolUseFailureOutput::default()
    ))]
    #[case::post_tool_batch(HookOutputEvent::PostToolBatch(PostToolBatchOutput::default()))]
    #[case::permission_denied(HookOutputEvent::PermissionDenied(PermissionDeniedOutput::default()))]
    #[case::subagent_start(HookOutputEvent::SubagentStart(SubagentStartOutput::default()))]
    #[case::subagent_stop(HookOutputEvent::SubagentStop(SubagentStopOutput::default()))]
    #[case::task_created(HookOutputEvent::TaskCreated(TaskCreatedOutput::default()))]
    #[case::task_completed(HookOutputEvent::TaskCompleted(TaskCompletedOutput::default()))]
    #[case::stop(HookOutputEvent::Stop(StopOutput::default()))]
    #[case::stop_failure(HookOutputEvent::StopFailure(EmptyOutput::default()))]
    #[case::teammate_idle(HookOutputEvent::TeammateIdle(TeammateIdleOutput::default()))]
    #[case::config_change(HookOutputEvent::ConfigChange(ConfigChangeOutput::default()))]
    #[case::post_compact(HookOutputEvent::PostCompact(PostCompactOutput::default()))]
    #[case::elicitation(HookOutputEvent::Elicitation(ElicitationOutput::default()))]
    #[case::elicitation_result(HookOutputEvent::ElicitationResult(EmptyOutput::default()))]
    fn test_exhaustive_hook_output_serialization_empty(
        #[case] out: HookOutputEvent,
    ) -> Result<(), TestError> {
        let serialized = serde_json::to_value(&out)?;
        assert_eq!(serialized, json!({}));
        Ok(())
    }

    #[rstest]
    fn test_hook_output_serialization_populated() -> Result<(), TestError> {
        let out = HookOutputEvent::SessionStart(SessionStartOutput {
            system_message: Some("hello".to_string()),
            ..Default::default()
        });

        assert_eq!(
            serde_json::to_value(&out)?,
            json!({"system_message": "hello"})
        );

        Ok(())
    }

    #[rstest]
    #[case::allow(PermissionBehavior::Allow, "allow")]
    #[case::deny(PermissionBehavior::Deny, "deny")]
    fn test_permission_request_output_serialization_behavior(
        #[case] behavior: PermissionBehavior,
        #[case] expected: &str,
    ) -> Result<(), TestError> {
        let out = HookOutputEvent::PermissionRequest(PermissionRequestOutput {
            behavior: Some(behavior),
            ..Default::default()
        });

        assert_eq!(serde_json::to_value(&out)?, json!({"behavior": expected}));

        Ok(())
    }

    #[rstest]
    #[case::pre_tool_use(HookOutputEvent::PreToolUse(PreToolUseOutput { exit_code: Some(1), ..Default::default() }), 1)]
    #[case::post_tool_use(HookOutputEvent::PostToolUse(PostToolUseOutput { exit_code: Some(2), ..Default::default() }), 2)]
    #[case::before_agent(HookOutputEvent::BeforeAgent(BeforeAgentOutput { exit_code: Some(3), ..Default::default() }), 3)]
    #[case::after_agent(HookOutputEvent::AfterAgent(AfterAgentOutput { exit_code: Some(4), ..Default::default() }), 4)]
    #[case::before_model(HookOutputEvent::BeforeModel(BeforeModelOutput { exit_code: Some(5), ..Default::default() }), 5)]
    #[case::after_model(HookOutputEvent::AfterModel(AfterModelOutput { exit_code: Some(6), ..Default::default() }), 6)]
    #[case::pre_compact(HookOutputEvent::PreCompact(PreCompactOutput { exit_code: Some(7), ..Default::default() }), 7)]
    fn test_all_exit_metadata_arms(
        #[case] output: HookOutputEvent,
        #[case] expected_code: i32,
    ) -> Result<(), TestError> {
        let (code, _) = output.exit_metadata();
        assert_eq!(code, Some(expected_code));
        Ok(())
    }

    #[rstest]
    #[case::returns_allow_decision_when_pre_tool_use_event_has_decision(HookOutputEvent::PreToolUse(PreToolUseOutput { decision: Some(Decision::Allow), ..Default::default() }), Some(Decision::Allow))]
    #[case::returns_block_decision_when_post_tool_use_event_has_decision(HookOutputEvent::PostToolUse(PostToolUseOutput { decision: Some(Decision::Block), ..Default::default() }), Some(Decision::Block))]
    #[case::returns_allow_decision_when_before_agent_event_has_decision(HookOutputEvent::BeforeAgent(BeforeAgentOutput { decision: Some(Decision::Allow), ..Default::default() }), Some(Decision::Allow))]
    #[case::returns_block_decision_when_after_agent_event_has_decision(HookOutputEvent::AfterAgent(AfterAgentOutput { decision: Some(Decision::Block), ..Default::default() }), Some(Decision::Block))]
    #[case::returns_allow_decision_when_before_model_event_has_decision(HookOutputEvent::BeforeModel(BeforeModelOutput { decision: Some(Decision::Allow), ..Default::default() }), Some(Decision::Allow))]
    #[case::returns_block_decision_when_after_model_event_has_decision(HookOutputEvent::AfterModel(AfterModelOutput { decision: Some(Decision::Block), ..Default::default() }), Some(Decision::Block))]
    #[case::returns_allow_decision_when_pre_compact_event_has_decision(HookOutputEvent::PreCompact(PreCompactOutput { decision: Some(Decision::Allow), ..Default::default() }), Some(Decision::Allow))]
    #[case::returns_block_decision_when_user_prompt_submit_event_has_decision(HookOutputEvent::UserPromptSubmit(UserPromptSubmitOutput { decision: Some(Decision::Block), ..Default::default() }), Some(Decision::Block))]
    #[case::returns_allow_decision_when_post_tool_use_failure_event_has_decision(HookOutputEvent::PostToolUseFailure(PostToolUseFailureOutput { decision: Some(Decision::Allow), ..Default::default() }), Some(Decision::Allow))]
    #[case::returns_block_decision_when_post_tool_batch_event_has_decision(HookOutputEvent::PostToolBatch(PostToolBatchOutput { decision: Some(Decision::Block), ..Default::default() }), Some(Decision::Block))]
    #[case::returns_allow_decision_when_config_change_event_has_decision(HookOutputEvent::ConfigChange(ConfigChangeOutput { decision: Some(Decision::Allow), ..Default::default() }), Some(Decision::Allow))]
    #[case::returns_block_decision_when_stop_event_has_decision(HookOutputEvent::Stop(StopOutput { decision: Some(Decision::Block), ..Default::default() }), Some(Decision::Block))]
    #[case::returns_allow_decision_when_user_prompt_expansion_event_has_decision(HookOutputEvent::UserPromptExpansion(UserPromptExpansionOutput { decision: Some(Decision::Allow), ..Default::default() }), Some(Decision::Allow))]
    #[case::returns_block_decision_when_subagent_stop_event_has_decision(HookOutputEvent::SubagentStop(SubagentStopOutput { decision: Some(Decision::Block), ..Default::default() }), Some(Decision::Block))]
    #[case::returns_allow_decision_when_task_created_event_has_decision(HookOutputEvent::TaskCreated(TaskCreatedOutput { decision: Some(Decision::Allow), ..Default::default() }), Some(Decision::Allow))]
    #[case::returns_block_decision_when_task_completed_event_has_decision(HookOutputEvent::TaskCompleted(TaskCompletedOutput { decision: Some(Decision::Block), ..Default::default() }), Some(Decision::Block))]
    #[case::returns_allow_decision_when_teammate_idle_event_has_decision(HookOutputEvent::TeammateIdle(TeammateIdleOutput { decision: Some(Decision::Allow), ..Default::default() }), Some(Decision::Allow))]
    #[case::returns_none_when_session_start_event_does_not_support_decision(
        HookOutputEvent::SessionStart(SessionStartOutput::default()),
        None
    )]
    fn test_hook_output_event_decision_accessor_returns_expected_decision(
        #[case] output: HookOutputEvent,
        #[case] expected: Option<Decision>,
    ) -> Result<(), TestError> {
        assert_eq!(output.decision(), expected);
        Ok(())
    }

    #[rstest]
    #[case::pre_tool_use(HookOutputEvent::PreToolUse(PreToolUseOutput::default()))]
    #[case::post_tool_use(HookOutputEvent::PostToolUse(PostToolUseOutput::default()))]
    #[case::before_agent(HookOutputEvent::BeforeAgent(BeforeAgentOutput::default()))]
    #[case::after_agent(HookOutputEvent::AfterAgent(AfterAgentOutput::default()))]
    #[case::before_model(HookOutputEvent::BeforeModel(BeforeModelOutput::default()))]
    #[case::after_model(HookOutputEvent::AfterModel(AfterModelOutput::default()))]
    #[case::pre_compact(HookOutputEvent::PreCompact(PreCompactOutput::default()))]
    #[case::user_prompt_submit(HookOutputEvent::UserPromptSubmit(
        UserPromptSubmitOutput::default()
    ))]
    #[case::post_tool_use_failure(HookOutputEvent::PostToolUseFailure(
        PostToolUseFailureOutput::default()
    ))]
    #[case::post_tool_batch(HookOutputEvent::PostToolBatch(PostToolBatchOutput::default()))]
    #[case::config_change(HookOutputEvent::ConfigChange(ConfigChangeOutput::default()))]
    #[case::stop(HookOutputEvent::Stop(StopOutput::default()))]
    #[case::user_prompt_expansion(HookOutputEvent::UserPromptExpansion(
        UserPromptExpansionOutput::default()
    ))]
    #[case::subagent_stop(HookOutputEvent::SubagentStop(SubagentStopOutput::default()))]
    #[case::task_created(HookOutputEvent::TaskCreated(TaskCreatedOutput::default()))]
    #[case::task_completed(HookOutputEvent::TaskCompleted(TaskCompletedOutput::default()))]
    #[case::teammate_idle(HookOutputEvent::TeammateIdle(TeammateIdleOutput::default()))]
    fn test_set_decision_overwrites_supported_variants(
        #[case] mut output: HookOutputEvent,
    ) -> Result<(), TestError> {
        output.set_decision(Decision::Ask);
        assert_eq!(output.decision(), Some(Decision::Ask));
        Ok(())
    }

    #[rstest]
    fn test_set_decision_overwrites_existing_decision() -> Result<(), TestError> {
        let mut output = HookOutputEvent::PreToolUse(PreToolUseOutput {
            decision: Some(Decision::Allow),
            ..Default::default()
        });

        output.set_decision(Decision::Deny);

        assert_eq!(output.decision(), Some(Decision::Deny));
        Ok(())
    }

    #[rstest]
    #[case::session_start(HookOutputEvent::SessionStart(SessionStartOutput::default()))]
    #[case::permission_request(HookOutputEvent::PermissionRequest(
        PermissionRequestOutput::default()
    ))]
    fn test_set_decision_is_noop_for_unsupported_variants(
        #[case] mut output: HookOutputEvent,
    ) -> Result<(), TestError> {
        output.set_decision(Decision::Ask);
        assert_eq!(output.decision(), None);
        Ok(())
    }

    #[rstest]
    #[case::returns_reason_string_when_pre_tool_use_event_has_reason(HookOutputEvent::PreToolUse(PreToolUseOutput { reason: Some("test".into()), ..Default::default() }), Some("test"))]
    #[case::returns_reason_string_when_post_tool_use_event_has_reason(HookOutputEvent::PostToolUse(PostToolUseOutput { reason: Some("denied".into()), ..Default::default() }), Some("denied"))]
    #[case::returns_reason_string_when_before_agent_event_has_reason(HookOutputEvent::BeforeAgent(BeforeAgentOutput { reason: Some("r".into()), ..Default::default() }), Some("r"))]
    #[case::returns_reason_string_when_after_agent_event_has_reason(HookOutputEvent::AfterAgent(AfterAgentOutput { reason: Some("r".into()), ..Default::default() }), Some("r"))]
    #[case::returns_reason_string_when_before_model_event_has_reason(HookOutputEvent::BeforeModel(BeforeModelOutput { reason: Some("r".into()), ..Default::default() }), Some("r"))]
    #[case::returns_reason_string_when_after_model_event_has_reason(HookOutputEvent::AfterModel(AfterModelOutput { reason: Some("r".into()), ..Default::default() }), Some("r"))]
    #[case::returns_reason_string_when_pre_compact_event_has_reason(HookOutputEvent::PreCompact(PreCompactOutput { reason: Some("r".into()), ..Default::default() }), Some("r"))]
    #[case::returns_reason_string_when_user_prompt_submit_event_has_reason(HookOutputEvent::UserPromptSubmit(UserPromptSubmitOutput { reason: Some("r".into()), ..Default::default() }), Some("r"))]
    #[case::returns_reason_string_when_post_tool_use_failure_event_has_reason(HookOutputEvent::PostToolUseFailure(PostToolUseFailureOutput { reason: Some("r".into()), ..Default::default() }), Some("r"))]
    #[case::returns_reason_string_when_post_tool_batch_event_has_reason(HookOutputEvent::PostToolBatch(PostToolBatchOutput { reason: Some("r".into()), ..Default::default() }), Some("r"))]
    #[case::returns_reason_string_when_config_change_event_has_reason(HookOutputEvent::ConfigChange(ConfigChangeOutput { reason: Some("r".into()), ..Default::default() }), Some("r"))]
    #[case::returns_reason_string_when_user_prompt_expansion_event_has_reason(HookOutputEvent::UserPromptExpansion(UserPromptExpansionOutput { reason: Some("r".into()), ..Default::default() }), Some("r"))]
    #[case::returns_reason_string_when_subagent_stop_event_has_reason(HookOutputEvent::SubagentStop(SubagentStopOutput { reason: Some("r".into()), ..Default::default() }), Some("r"))]
    #[case::returns_reason_string_when_task_created_event_has_reason(HookOutputEvent::TaskCreated(TaskCreatedOutput { reason: Some("r".into()), ..Default::default() }), Some("r"))]
    #[case::returns_reason_string_when_task_completed_event_has_reason(HookOutputEvent::TaskCompleted(TaskCompletedOutput { reason: Some("r".into()), ..Default::default() }), Some("r"))]
    #[case::returns_reason_string_when_teammate_idle_event_has_reason(HookOutputEvent::TeammateIdle(TeammateIdleOutput { reason: Some("r".into()), ..Default::default() }), Some("r"))]
    #[case::returns_none_when_stop_event_does_not_support_reason(
        HookOutputEvent::Stop(StopOutput::default()),
        None
    )]
    #[case::returns_none_when_session_start_event_does_not_support_reason(
        HookOutputEvent::SessionStart(SessionStartOutput::default()),
        None
    )]
    fn test_hook_output_event_reason_accessor_returns_expected_reason(
        #[case] output: HookOutputEvent,
        #[case] expected: Option<&str>,
    ) -> Result<(), TestError> {
        assert_eq!(output.reason(), expected);
        Ok(())
    }

    #[rstest]
    #[case::returns_true_when_pre_tool_use_event_has_halt_flag_set(HookOutputEvent::PreToolUse(PreToolUseOutput { halt: Some(true), ..Default::default() }), Some(true))]
    #[case::returns_false_when_post_tool_use_event_has_halt_flag_unset(HookOutputEvent::PostToolUse(PostToolUseOutput { halt: Some(false), ..Default::default() }), Some(false))]
    #[case::returns_true_when_before_agent_event_has_halt_flag_set(HookOutputEvent::BeforeAgent(BeforeAgentOutput { halt: Some(true), ..Default::default() }), Some(true))]
    #[case::returns_true_when_after_agent_event_has_halt_flag_set(HookOutputEvent::AfterAgent(AfterAgentOutput { halt: Some(true), ..Default::default() }), Some(true))]
    #[case::returns_true_when_before_model_event_has_halt_flag_set(HookOutputEvent::BeforeModel(BeforeModelOutput { halt: Some(true), ..Default::default() }), Some(true))]
    #[case::returns_true_when_after_model_event_has_halt_flag_set(HookOutputEvent::AfterModel(AfterModelOutput { halt: Some(true), ..Default::default() }), Some(true))]
    #[case::returns_none_when_session_start_event_does_not_support_halt_flag(
        HookOutputEvent::SessionStart(SessionStartOutput::default()),
        None
    )]
    fn test_hook_output_event_halt_accessor_returns_expected_halt_flag(
        #[case] output: HookOutputEvent,
        #[case] expected: Option<bool>,
    ) -> Result<(), TestError> {
        assert_eq!(output.halt(), expected);
        Ok(())
    }

    #[rstest]
    #[case::returns_true_when_post_tool_use_event_has_suppress_output_set(HookOutputEvent::PostToolUse(PostToolUseOutput { suppress_output: Some(true), ..Default::default() }), Some(true))]
    #[case::returns_none_when_post_tool_use_event_omits_suppress_output_flag(
        HookOutputEvent::PostToolUse(PostToolUseOutput::default()),
        None
    )]
    #[case::returns_none_when_pre_tool_use_event_does_not_support_suppress_output(
        HookOutputEvent::PreToolUse(PreToolUseOutput::default()),
        None
    )]
    fn test_hook_output_event_suppress_output_accessor_returns_expected_flag(
        #[case] output: HookOutputEvent,
        #[case] expected: Option<bool>,
    ) -> Result<(), TestError> {
        assert_eq!(output.suppress_output(), expected);
        Ok(())
    }

    #[rstest]
    #[case::returns_message_string_when_session_start_event_has_system_message(HookOutputEvent::SessionStart(SessionStartOutput { system_message: Some("hello".into()), ..Default::default() }), Some("hello"))]
    #[case::returns_message_string_when_session_end_event_has_system_message(HookOutputEvent::SessionEnd(SessionEndOutput { system_message: Some("bye".into()) }), Some("bye"))]
    #[case::returns_message_string_when_notification_event_has_system_message(HookOutputEvent::Notification(NotificationOutput { system_message: Some("msg".into()) }), Some("msg"))]
    #[case::returns_message_string_when_pre_compact_event_has_system_message(HookOutputEvent::PreCompact(PreCompactOutput { system_message: Some("msg".into()), ..Default::default() }), Some("msg"))]
    #[case::returns_message_string_when_instructions_loaded_event_has_system_message(HookOutputEvent::InstructionsLoaded(InstructionsLoadedOutput { system_message: Some("msg".into()) }), Some("msg"))]
    #[case::returns_message_string_when_post_compact_event_has_system_message(HookOutputEvent::PostCompact(PostCompactOutput { system_message: Some("msg".into()) }), Some("msg"))]
    #[case::returns_none_when_pre_tool_use_event_does_not_support_system_message(
        HookOutputEvent::PreToolUse(PreToolUseOutput::default()),
        None
    )]
    fn test_hook_output_event_system_message_accessor_returns_expected_message(
        #[case] output: HookOutputEvent,
        #[case] expected: Option<&str>,
    ) -> Result<(), TestError> {
        assert_eq!(output.system_message(), expected);
        Ok(())
    }
}
