//! # Read-Write-Guard Architecture
//!
//! The Read-Write-Guard stage acts as a defensive shield around ecosystem
//! lockfiles and manifests, on both ends: it stops the agent from manually
//! *writing* them, and discourages it from *reading* them directly.
//!
//! ## Core Design
//!
//! Many AI agents natively attempt to `Write` or `Edit` files like
//! `flake.lock` or `Cargo.lock` when told to update dependencies. These files
//! are typically autogenerated and manually editing them can easily break
//! build reproducibility or introduce subtle hash-mismatch errors. Reading
//! them is similarly unproductive: they're large, dense, and provide little
//! signal relative to the context they consume.
//!
//! Read-Write-Guard intercepts both:
//! - **Writes** are denied and redirected to the proper ecosystem-native
//!   tooling (e.g. `nix flake update`, `cargo update`, `npm install`).
//! - **Reads** are denied with a generic reminder that the file is
//!   machine-generated noise, pointing the agent at `git diff` instead.
//!
//! ## Supported Ecosystems
//!
//! This crate itself has no notion of "built-in" rules — the guarded-file
//! list (Nix, Node.js, Rust, Python, Go, and others) lives in the binary's
//! default config, `src/config/base.toml`; see [Configuration](#configuration).
//!
//! ## Implementation Details
//!
//! 1. **Target Identification**: Filters `PreToolUse` events for both
//!    modifying tools (`Write`, `Edit`, `MultiEdit`, `write_file`, `replace`)
//!    and reading tools (`READ_TOOLS`).
//! 2. **Path Matching**: Looks up the target path in [`types::RuleSet`]. Each
//!    [`types::Rule`]'s pattern is one of three forms: an exact basename
//!    (`Cargo.lock`, checked first via a `BTreeMap` — `O(log n)`, no linear
//!    scan), a basename glob (`*.pb.go`), or — if it contains `/` — a
//!    full-path glob (`**/node_modules/**`, gitignore-style: a leading
//!    `**/` matches at any depth). Glob/path patterns are compiled once and
//!    checked in a fallback linear scan only when the exact lookup misses.
//! 3. **Response Generation**: Each [`types::Rule`] carries an
//!    [`types::Access`] policy that determines, per tool kind, whether the
//!    action is denied and what the denial reason looks like — modifying
//!    tools get a targeted hint containing the correct terminal command to
//!    use instead; reading tools get a generic "this is noise, use `git
//!    diff`" reminder. All built-in rules use [`Access::No`] (deny both,
//!    with those two messages).
//!
//! [`Access::Diff`] is a reserved policy for a future upgrade of any rule
//! (built-in or user-supplied): it's meant to replace the generic
//! read-denial with a real diff/summary once that's implemented. For now it
//! behaves identically to [`Access::No`].
//! [`FlakeLockSummarizationStage`](crate::FlakeLockSummarizationStage),
//! registered earlier in the pipeline, already provides this kind of summary
//! for `flake.lock` reads specifically — this stage's [`Access::No`]
//! read-deny is the fallback for everything else (and for `flake.lock` when
//! that stage is a no-op).
//!
//! ## Configuration
//!
//! [`ReadWriteGuardStage`] takes a fully resolved [`RuleSet`] — this crate
//! has no notion of "built-in" rules or config files. The binary's config
//! layer (`src/config`) owns the built-in defaults (embedded alongside the
//! rest of its base config) and merges any user overrides in before
//! constructing the stage via [`ReadWriteGuardStage::new`].

mod types;

pub use types::{Access, Rule, RuleSet};

use inceptool_engine::{EngineError, Stage};
use inceptool_protocol::{
    Conn, Decision, HookInputEvent, HookKind, HookOutputEvent, PreToolUseOutput, extract_file_path,
};

use serde_json::Value;

/// Tool names whose `PreToolUse` event reads a file's contents.
const READ_TOOLS: &[&str] = &["Read", "view_file", "cat"];

/// Stage that denies direct reads and writes of ecosystem lockfiles.
#[derive(Debug, Clone)]
pub struct ReadWriteGuardStage {
    rules: RuleSet,
}

impl Stage for ReadWriteGuardStage {
    fn name(&self) -> &'static str {
        "read-write-guard"
    }

    fn hook(&self) -> HookKind {
        HookKind::PreToolUse
    }

    fn tool_names(&self) -> &'static [&'static str] {
        &[
            "Write",
            "Edit",
            "MultiEdit",
            "write_file",
            "replace",
            "Read",
            "view_file",
            "cat",
        ]
    }

    fn run(&self, conn: &mut Conn<'_>) -> Result<Option<HookOutputEvent>, EngineError> {
        if let HookInputEvent::PreToolUse(input) = &conn.event {
            let parsed: Value = input.parse_tool_input()?;

            let Some(file_path) = extract_file_path(&parsed) else {
                return Ok(None);
            };

            let Some((rule, display_name)) = self.rules.get(file_path) else {
                return Ok(None);
            };

            let is_read_tool = READ_TOOLS.contains(&input.tool_name.as_ref());

            let Some(output) = dispatch(display_name, rule, is_read_tool) else {
                return Ok(None);
            };

            return Ok(Some(HookOutputEvent::PreToolUse(output)));
        }
        Ok(None)
    }
}

impl ReadWriteGuardStage {
    /// Builds the stage from a fully resolved [`RuleSet`] (the caller is
    /// responsible for merging built-in defaults with any user overrides).
    #[must_use = "constructs a new stage; discarding it does nothing"]
    pub const fn new(rules: RuleSet) -> Self {
        Self { rules }
    }
}

/// Dispatches a guarded-file access: returns the [`Decision::Deny`] response
/// for `rule`'s policy and the current tool kind, or `None` if `rule.access`
/// allows this operation to pass through untouched. `display_name` is what
/// [`RuleSet::get`] returned alongside the rule — the basename for
/// exact/basename-glob matches, the full path for path-glob matches.
fn dispatch(display_name: &str, rule: &Rule, is_read_tool: bool) -> Option<PreToolUseOutput> {
    match (rule.access(), is_read_tool) {
        (Access::Write { .. }, true) | (Access::Read, false) => None,
        (_, true) => Some(deny_read(display_name)),
        (
            Access::No { hint, note } | Access::Diff { hint, note } | Access::Write { hint, note },
            false,
        ) => Some(deny_write(display_name, hint, note)),
    }
}

/// Builds the [`Decision::Deny`] response for a denied read of
/// `display_name`.
fn deny_read(display_name: &str) -> PreToolUseOutput {
    PreToolUseOutput {
        decision: Some(Decision::Deny),
        reason: Some(
            format!(
                "Reading {display_name} directly wastes context \u{2014} it's \
                 machine-generated or otherwise low-signal. Run `git diff \
                 {display_name}` to see what changed."
            )
            .into(),
        ),
        ..Default::default()
    }
}

/// Builds the [`Decision::Deny`] response for a denied write of
/// `display_name`, using the matched [`Access`] variant's `hint` and `note`.
fn deny_write(display_name: &str, hint: &str, note: &str) -> PreToolUseOutput {
    PreToolUseOutput {
        decision: Some(Decision::Deny),
        reason: Some(format!("Writing to {display_name} is not allowed. {hint} {note}").into()),
        ..Default::default()
    }
}

#[cfg(test)]
mod tests {
    use super::*;

    use inceptool_protocol::{BeforeAgentInput, PreToolUseInput, RawJson, SessionMeta};

    use rstest::rstest;
    use serde_json::json;
    use serde_json::value::RawValue;

    use std::borrow::Cow;
    use std::collections::BTreeSet;

    #[derive(thiserror::Error, Debug)]
    enum TestError {
        #[error(transparent)]
        Engine(#[from] EngineError),
        #[error(transparent)]
        Json(#[from] serde_json::Error),
        #[error("Test failure: {0}")]
        Failure(String),
    }

    /// A small fixture [`RuleSet`] standing in for what the binary's config
    /// layer would otherwise build from its base config + user overrides —
    /// this crate has no notion of "built-in" rules of its own.
    fn test_rules() -> RuleSet {
        [
            Rule::new(
                Cow::Borrowed("flake.lock"),
                Access::No {
                    hint: Cow::Borrowed("Run `nix flake update` to update it."),
                    note: Cow::Borrowed("(NOTE: updates ALL flake inputs)"),
                },
            ),
            Rule::new(
                Cow::Borrowed("Cargo.lock"),
                Access::No {
                    hint: Cow::Borrowed("Run `cargo update` to update it."),
                    note: Cow::Borrowed("(NOTE: updates ALL Rust dependencies)"),
                },
            ),
            Rule::new(
                Cow::Borrowed("package-lock.json"),
                Access::No {
                    hint: Cow::Borrowed("Run `npm install` to update it."),
                    note: Cow::Borrowed("(NOTE: updates ALL node packages)"),
                },
            ),
        ]
        .into_iter()
        .collect()
    }

    /// Builds a synthetic `Conn` wrapping `event`, with placeholder session metadata.
    fn conn_with_event(event: HookInputEvent<'_>) -> Conn<'_> {
        Conn {
            session: SessionMeta {
                session_id: Cow::Borrowed("session-1"),
                transcript_path: None,
                cwd: None,
                timestamp: None,
                driver: Cow::Borrowed("Test"),
                driver_meta: None,
                permission_mode: None,
                effort: None,
                agent_id: None,
                agent_type: None,
            },
            event,
        }
    }

    /// Runs [`ReadWriteGuardStage`] against a synthetic `PreToolUse` event for
    /// `tool_name` with the given `tool_input_json` (e.g. `{"file_path": "..."}`).
    fn run_stage_with_tool_input(
        tool_name: &str,
        tool_input_json: &str,
    ) -> Result<Option<HookOutputEvent>, TestError> {
        let stage = ReadWriteGuardStage::new(test_rules());
        let tool_input = RawValue::from_string(tool_input_json.to_owned())?;

        let mut conn = conn_with_event(HookInputEvent::PreToolUse(PreToolUseInput {
            tool_name: Cow::Borrowed(tool_name),
            tool_input: RawJson(&tool_input),
            mcp_context: None,
            original_request_name: None,
        }));

        Ok(stage.run(&mut conn)?)
    }

    /// Runs [`ReadWriteGuardStage`] against a synthetic `PreToolUse` event for
    /// `tool_name` targeting `file_path`.
    fn run_stage(tool_name: &str, file_path: &str) -> Result<Option<HookOutputEvent>, TestError> {
        run_stage_with_tool_input(tool_name, &json!({"file_path": file_path}).to_string())
    }

    /// Extracts the `reason` from a `PreToolUse` `Deny` output, failing the test otherwise.
    fn deny_reason(output: Option<HookOutputEvent>) -> Result<String, TestError> {
        let HookOutputEvent::PreToolUse(pre) =
            output.ok_or_else(|| TestError::Failure("expected a hook output".into()))?
        else {
            return Err(TestError::Failure("expected a PreToolUse output".into()));
        };

        assert_eq!(pre.decision, Some(Decision::Deny));

        pre.reason
            .map(Cow::into_owned)
            .ok_or_else(|| TestError::Failure("missing reason".into()))
    }

    /// Builds a synthetic [`Rule`] with `access`, for exercising [`dispatch`]
    /// directly without going through [`test_rules`].
    const fn rule_with_access(access: Access) -> Rule {
        Rule::new(Cow::Borrowed("test.lock"), access)
    }

    #[rstest]
    #[case::flake_lock("flake.lock", "nix flake update")]
    #[case::cargo_lock("Cargo.lock", "cargo update")]
    #[case::package_lock("package-lock.json", "npm install")]
    fn denies_write_with_hint(
        #[case] file_name: &str,
        #[case] hint_fragment: &str,
    ) -> Result<(), TestError> {
        let reason = deny_reason(run_stage("Edit", &format!("/repo/{file_name}"))?)?;

        assert!(reason.starts_with(&format!("Writing to {file_name} is not allowed.")));
        assert!(reason.contains(hint_fragment));

        Ok(())
    }

    #[rstest]
    #[case::flake_lock("flake.lock")]
    #[case::cargo_lock("Cargo.lock")]
    #[case::package_lock("package-lock.json")]
    fn denies_read_with_generic_reason(#[case] file_name: &str) -> Result<(), TestError> {
        let reason = deny_reason(run_stage("Read", &format!("/repo/{file_name}"))?)?;

        assert!(reason.starts_with(&format!("Reading {file_name} directly wastes context")));
        assert!(reason.contains(&format!("git diff {file_name}")));

        Ok(())
    }

    #[rstest]
    #[case::write_tool("Write")]
    #[case::read_tool("Read")]
    fn ignores_unguarded_file(#[case] tool_name: &str) -> Result<(), TestError> {
        assert!(run_stage(tool_name, "/repo/src/main.rs")?.is_none());
        Ok(())
    }

    #[rstest]
    #[case::write_tool("Write")]
    #[case::read_tool("Read")]
    fn ignores_missing_file_path(#[case] tool_name: &str) -> Result<(), TestError> {
        assert!(run_stage_with_tool_input(tool_name, "{}")?.is_none());
        Ok(())
    }

    #[rstest]
    fn ignores_non_pre_tool_use_event() -> Result<(), TestError> {
        let stage = ReadWriteGuardStage::new(test_rules());

        let mut conn = conn_with_event(HookInputEvent::BeforeAgent(BeforeAgentInput {
            prompt: Cow::Borrowed("rm -rf /"),
        }));

        assert!(stage.run(&mut conn)?.is_none());

        Ok(())
    }

    /// Tool names whose `PreToolUse` event writes a file's contents.
    const WRITE_TOOLS: &[&str] = &["Write", "Edit", "MultiEdit", "write_file", "replace"];

    #[rstest]
    fn tool_names_matches_read_and_write_tools() {
        let stage = ReadWriteGuardStage::new(test_rules());

        let expected: BTreeSet<&str> = READ_TOOLS.iter().chain(WRITE_TOOLS).copied().collect();
        let actual: BTreeSet<&str> = stage.tool_names().iter().copied().collect();

        assert_eq!(actual, expected);
    }

    #[rstest]
    #[case::no(Access::No { hint: Cow::Borrowed("<hint>"), note: Cow::Borrowed("<note>") })]
    #[case::diff(Access::Diff { hint: Cow::Borrowed("<hint>"), note: Cow::Borrowed("<note>") })]
    #[case::read(Access::Read)]
    fn dispatch_denies_read_with_generic_reason(#[case] access: Access) -> Result<(), TestError> {
        let rule = rule_with_access(access);
        let output = dispatch("test.lock", &rule, true)
            .ok_or_else(|| TestError::Failure("expected a deny".into()))?;

        assert_eq!(output.decision, Some(Decision::Deny));

        let reason = output
            .reason
            .map(Cow::into_owned)
            .ok_or_else(|| TestError::Failure("missing reason".into()))?;
        assert!(reason.starts_with("Reading test.lock directly wastes context"));
        assert!(reason.contains("git diff test.lock"));

        Ok(())
    }

    #[rstest]
    #[case::no(Access::No { hint: Cow::Borrowed("<hint>"), note: Cow::Borrowed("<note>") })]
    #[case::diff(Access::Diff { hint: Cow::Borrowed("<hint>"), note: Cow::Borrowed("<note>") })]
    #[case::write(Access::Write { hint: Cow::Borrowed("<hint>"), note: Cow::Borrowed("<note>") })]
    fn dispatch_denies_write_with_hint(#[case] access: Access) -> Result<(), TestError> {
        let rule = rule_with_access(access);
        let output = dispatch("test.lock", &rule, false)
            .ok_or_else(|| TestError::Failure("expected a deny".into()))?;

        assert_eq!(output.decision, Some(Decision::Deny));

        let reason = output
            .reason
            .map(Cow::into_owned)
            .ok_or_else(|| TestError::Failure("missing reason".into()))?;
        assert!(reason.starts_with("Writing to test.lock is not allowed."));
        assert!(reason.contains("<hint>"));
        assert!(reason.contains("<note>"));

        Ok(())
    }

    #[rstest]
    #[case::write_access_read_tool(Access::Write { hint: Cow::Borrowed("<hint>"), note: Cow::Borrowed("<note>") }, true)]
    #[case::read_access_write_tool(Access::Read, false)]
    fn dispatch_passes_through_unrestricted_operation(
        #[case] access: Access,
        #[case] is_read_tool: bool,
    ) {
        let rule = rule_with_access(access);
        assert!(dispatch("test.lock", &rule, is_read_tool).is_none());
    }

    mod glob_patterns {
        use super::*;

        /// A [`RuleSet`] mixing a basename glob and a path glob, for
        /// exercising the stage end-to-end through non-exact matches.
        fn glob_rules() -> RuleSet {
            [
                Rule::new(
                    Cow::Borrowed("*.pb.go"),
                    Access::Write {
                        hint: Cow::Borrowed("Regenerate from the .proto file."),
                        note: Cow::Borrowed("(NOTE: fully regenerated on every protoc run)"),
                    },
                ),
                Rule::new(
                    Cow::Borrowed("**/node_modules/**"),
                    Access::No {
                        hint: Cow::Borrowed("Run `npm install` to manage dependencies."),
                        note: Cow::Borrowed("(NOTE: regenerated entirely by the package manager)"),
                    },
                ),
            ]
            .into_iter()
            .collect()
        }

        /// Same as [`run_stage`], but against [`glob_rules`] instead of
        /// [`test_rules`].
        fn run_glob_stage(
            tool_name: &str,
            file_path: &str,
        ) -> Result<Option<HookOutputEvent>, TestError> {
            let stage = ReadWriteGuardStage::new(glob_rules());
            let tool_input_json = json!({"file_path": file_path}).to_string();
            let tool_input = RawValue::from_string(tool_input_json)?;

            let mut conn = conn_with_event(HookInputEvent::PreToolUse(PreToolUseInput {
                tool_name: Cow::Borrowed(tool_name),
                tool_input: RawJson(&tool_input),
                mcp_context: None,
                original_request_name: None,
            }));

            Ok(stage.run(&mut conn)?)
        }

        #[rstest]
        fn denies_write_for_basename_glob_match() -> Result<(), TestError> {
            let reason = deny_reason(run_glob_stage("Edit", "/repo/api/service.pb.go")?)?;

            assert!(reason.starts_with("Writing to service.pb.go is not allowed."));
            assert!(reason.contains("Regenerate from the .proto file."));

            Ok(())
        }

        #[rstest]
        fn denies_read_for_path_glob_match_with_full_path_in_reason() -> Result<(), TestError> {
            let path = "/repo/node_modules/lodash/index.js";
            let reason = deny_reason(run_glob_stage("Read", path)?)?;

            assert!(reason.starts_with(&format!("Reading {path} directly wastes context")));
            assert!(reason.contains(&format!("git diff {path}")));

            Ok(())
        }
    }
}
